### ISSUE TITLE
Create Acceptance testing matrix for Qubes 4.2 SecureDrop Workstation release

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#1044]
See existing 4.1 acceptance tests: https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests

To support efforts during the feature freeze period, it would be helpful to have a test matrix defining acceptance criteria for SDW 1.0.0, tracking progress towards them, and linking to either automated tests or manual test instructions for each item.

One optional but possibly useful feature would be columns for equivalent features in the Qubes 4.1 version, but if we don't include those then at we should at least use the 4.1 acceptance tests as a starting point.

**Comment by rocodes** [comment]
I updated the acceptance testing wiki to include couple things we've added since the last round of testing, and also some suggested on how to break up testing between people so we have some different focus areas and spend more time looking at the thing they are testing rather than trying to haul through the whole test plan, for example something like

-     Tester A: User story: International user. il8n/locale testing, network tests (Tor/JI), large file sizes (submit/download/view/export)
-     Tester B: User story: Longstanding user. Export scenarios, multiple file type previews (including zip files), source and conversation deletion scenarios. [Eventually: integrations, eg Signal, DZ].
-     Tester C: User story: new user (making notes on ease of use and usability, assume lack of Qubes mental model): provisioning, updater testing; sd-log testing, docs review
 
In terms of acceptance criteria, I think the wiki is approximately correct; in terms of 'progress towards', I'm personally fine with this issue or a spreadsheet whatever you prefer.

The big themes I'm thinking about are:
* Provisioning (our docs are correct, provisioning plus verification that things like RPC policies are in place; updates complete successfully, relevant due to changes in RPC policy, policy manager, systemd stuff, etc)
* Updating (updates complete as expected, update errors are visible, our docs accurately describe troubleshooting; its own theme just because we have so many provisioning changes that they probably warrant separate areas)
* Handling peripherals (relevant due to: device widget changes, export changes) 
* Internationalization and/or a11y (always relevant!, updated OS and some feature changes-> make sure no regressions, even if we are still WIP here)

but i'm just shooting from the hip there so open to other suggestions.
