### ISSUE TITLE
Create an API proxy as a qrexec service

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#107]
In order to build a graphical client that can live in a VM without Internet access, we want to create a [`qrexec` service](https://www.qubes-os.org/news/2017/10/03/core3/#qubes-remote-execution-qrexec-the-underlying-integration-framework) that can be used for accessing the [SecureDrop Journalist API](https://github.com/freedomofpress/securedrop/issues/1761), but for nothing else. 

This `securedrop-api-proxy` would live in the Internet-connected `sd-journalist` VM and be accessed from the `sd-svs` VM, which does not have Internet access.

This task splits roughly into the following sub-tasks, all of which are in the scope of the 7/11 - 7/25 sprint:

- [x] Define a protocol for the API proxy
- [x] Implement the API proxy itself.
- [x] Implement the scaffolding for a qrexec service in Qubes, without the actual API proxy implementation

See #88 for additional background.

**Comment by redshiftzero** [comment]
my claim is that if we do anything but dumbly pass requests and responses we're going to add a lot of complexity/maintenance burden for (almost) no win. That said, for the sake of argument, here are two possible minor security advantages to an alternative approach where the qrexec service is not just dumbly passing requests/responses back and forth:

- if we were to do parsing and validation of the API responses in the `sd-journalist` AppVM instead of `sd-svs` we reduce slightly attack surface on the SVS AppVM
- restricting the API calls that one can even make from the `sd-svs` AppVM to a set of whitelisted requests reduces what a malicious workstation can do to the server (not a compelling reason imho, because the malicious user would also have the private key, onion address, HidServAuth cookie, and valid API token for the journalist interface which already enables them to do plenty after exfil of this data)

I don't think either of these justify the additional complexity, but wanted to raise this in case anyone else sees any other advantages

**Comment by emkll** [comment]
I agree, @redshiftzero, I think using a very simple proxy makes sense, as the primary goal is to restrict network connectivity of `sd-svs`, similar to how qubes uses qrexec to proxy apt/yum traffic for template VMs.

Parsing/validating API responses on `sd-journalist` implies a malicious app server, in which case it's already game over. We should instead focus our efforts in validating responses in `sd-svs` (i.e. `securedrop-client`).

**Comment by joshuathayer** [comment]
These points basically make sense to me. In this model, should *all* components of the eventual HTTP request be provided by `sd-svs` to the proxy? Or should the server's `.onion` address be configured by a local file on `sd-proxy`, so the proxy wouldn't be able to be used as a generic HTTP proxy? Does that make sense? I lean away from allowing the hostname to be provided at request time.

**Comment by redshiftzero** [comment]
Good question... I agree, I think the onion address should not be configurable in the `sd-svs` AppVM because it would make it easier to exfiltrate information to an attacker-controlled server if an attacker gets code execution in the `sd-svs` AppVM

**Comment by joshuathayer** [comment]
@redshiftzero , @conorsch and me met and decided on a few things, which I'll document here.

### qrexec proxy overview

We confirmed that a new `sd-proxy` VM (which takes the place of the `sd-journalist` VM) should expose a `qrexec` service called by `sd-svs`, which takes request objects and returns response objects (as documented below). We agreed that the proxy should be relatively simple: it should be stateless, it should not try to limit requests by whitelist or blacklist, and it should not try too hard to abstract the REST/HTTP nature of the API it's proxying to. However, we decided that the hostname of the SD server should be configured in `sd-proxy`, rather than being included in the request object generated by `sd-svs` (which is to say, the proxy can only make requests against the configured server, and not make requests to arbitrary `.onion` URLs provided by `sd-svs`).

### authentication

Since the proxy is stateless, the normal authentication flow needs to be carried out by the client in `sd-svs`. Of course, this will be done through the proxy, but importantly the client code needs to carry out the auth process and handle the auth token returned by the server, and include it in all requests.

### handling large responses

We considered the issue of large responses: originally we though we'd just pass all requests and responses as JSON objects, serialized and deserialized in memory, but since it's possible we'll be handling responses which include files on the order of 500MB, we were wary of excess memory consumption. We came up with a scheme where non-JSON (read: file download) responses from the server would be saved directly to disk with random filename, then `qvm-move`d to `sd-svs`. The response to the `qrexec` request would include the name of the newly-written file on the local (to `sd-svs`) filesystem. So, we leverage Qubes' established tools for moving potentially-large files around, and keep our own `qrexec` payloads small.

### proxy version in response to sd-svs

Finally, we decided that we wanted to include the `sd-proxy` version in the response given to `sd-svs`. I'll let @redshiftzero and @conorsch comment more about why we chose only to include a version there, but it should allow updated versions of `sd-svs` detect an out-of-date `sd-proxy`, and either handle the version problem gracefully or show an error to the user.

### Request and response objects

It's worth reiterating that the proxy we're describing is a `qrexec` service, not a network service. It may be helpful to think of it in the model of an RPC call: we call a function with some arguments, and the function returns some data to us. The data we provide the RPC call is the request object shown below, the data it returns will be in the shape of the response object.

Our objects don't try to _hide_ the REST nature of our API (for example, both the request and response objects include HTTP headers), but they're not HTTP requests and responses per se.

    request:
        http_method (GET/POST/etc)
        path_query (a string: the path and query parts of https://en.wikipedia.org/wiki/URL#Syntax)
        body (an optional string: will be used unchanged in the body of the HTTP request)
        headers (an optional dictionary: will be used as the headers of the HTTP request)

    response:
        status_code (as returned from the server, maybe with additional codes indicating local-to-proxy errors)
        body (as returned from the server if the content-type was application/json, otherwise a JSON object indicating where the returned data was saved locally)
        headers (as returned from the server)
        version (of sd-proxy itself)

**Comment by conorsch** [comment]
> I'll let @redshiftzero and @conorsch comment more about why we chose only to include a version there

The idea is to offload all responsibility for managing version compatibility to the client. The `sd-svs` client will have access to its own version number, naturally, and forcing `sd-proxy` (again, replacing `sd-journalist`) pass its own version number will enable meaningful version comparison.

Given our current understanding of automatic update options within Qubes, it's quite possible that `sd-proxy` and `sd-svs` will be running different versions briefly, even on a system receiving regular updates in a timely fashion. Assuming we ship updates to TemplateVMs, only future instantiations of said templates will receive the latest code. Depending on when SecureDrop Workstation services are started on a given boot, it's possible some machines are created on slightly different versions of the template. Ideally, minor version drift won't break API compatibility—but we'd rather be equipped to decide meaningfully if necessary.

The client will always have the ability to self-serve _server-side_ versions of the API by modifying the route used to interact with the API. 

> It's worth reiterating that the proxy we're describing is a `qrexec` service, not a network service.

Also worth reiterating: `sd-svs` does not have a network interface, so `qrexec` is the sanest option, given our threat model. If we opted for a network service, we'd open up substantial attack surface, and require bmore fine-grained management of the VM orchestration to whitelist firewall rules. Using `qrexec` largely sidesteps the need to reinvent the wheel on inter-VM communication within Qubes.

**Comment by kushaldas** [comment]
>The idea is to offload all responsibility for managing version compatibility to the client. The sd-svs client will have access to its own version number, naturally, and forcing sd-proxy (again, replacing sd-journalist) pass its own version number will enable meaningful version comparison.
>Given our current understanding of automatic update options within Qubes, it's quite possible that sd-proxy and sd-svs will be running different versions briefly, even on a system receiving regular updates in a timely fashion. 

If we follow the Qubes APPvm strategy, then all dependencies should be always synced. The tools and the dependencies should always be packaged and installed in the TemplateVM. So that the proxy vm (with network access) and the client vm (without network access) should be synced **API level** while talking to each other. This can be achieved by creating both parts of the tool using from the same source level package.

>The client will always have the ability to self-serve server-side versions of the API by modifying the route used to interact with the API.

The above mentioned line (and the corresponding code) means we are not planning to use `securedrop-sdk` project, and it also means we are not planing to force version match in all of our dependencies. Even though we are developing the tools, unless we make sure that every package follows strict version dependencies, it will be difficult to update (using automated updates from distribution level package repositories). 

For the below points, please let me know if I am wrong in the assumption.

Looking at the existing proxy code base, I feel that the current implementation assumes the *client* side code will know how to talk to the server API. But, that makes the client to be a monolithic codebase and also the proxy has all the network call code which I think can be replaced by Python *requests* module.

# Example of another implementation using a Python module

I have a [repository](https://github.com/kushaldas/sequredrop-qubesproxy) where we have a Python module [sdqubes](https://github.com/kushaldas/sequredrop-qubesproxy/blob/master/sdqubes/__init__.py) which provides function calls to be used by the desktop client. This module talks to a proxy vm using the *qrexec* service and uses `securedrop-sdk` as the actual network dependency to talk to the server. Please check the [example.py](https://github.com/kushaldas/sequredrop-qubesproxy/blob/master/example.py) for usage details.

The [README](https://github.com/kushaldas/sequredrop-qubesproxy/blob/master/README.md) has detailed steps along with link to rpm files (for Fedora 28) which can be installed  in a TemplateVM.  If you want to see how it is packaged, please check the [SPEC](https://github.com/kushaldas/sequredrop-qubesproxy/blob/master/spec/securedrop-qubesproxy.spec) file.

In this PoC example, the client only provides username, password, and the otp value to login and then keep talking to the server. The host onion address is configured in the proxy vm. This can also be passed from the client to the proxy if required. Also tests and documentation will require work :)

Because of our Python dependencies, and knowing Fedora's packaging echosystem, I still believe that we can maintain this as rpm packages with an easier process.

Note: I wrote the `sdqubes` module in few hours, means it is not feature complete. Also I will  have to update the code so that we can have better control on how to connect to Tor (say a whonix vm). And this also means it will require work on documentation and a proper way test code.

**Comment by kushaldas** [comment]
>Why would we introduce this unnecessary coupling?

Because my initial idea was that proxy will use *securedrop-sdk* to do the network calls to the server. That way it makes sure that proxy can only be used to talk the configured server and nothing else.

Coming back to the packaging story, I have updated my example project with [instructions for Debian 9 based template](https://github.com/kushaldas/sequredrop-qubesproxy#securedrop-qubes-proxy). @redshiftzero @conorsch Please try out those steps and tell me what do you think. Meanwhile I am trying to figure out the configuration file handling story for our Debian packaging.

**Comment by eloquence** [comment]
I've removed the Debian packaging from the scope of this ticket; it's tracked here: https://github.com/freedomofpress/securedrop-proxy/issues/6 (with the meta-issue being https://github.com/freedomofpress/securedrop-workstation/issues/136). Accordingly we can close this one.
