### ISSUE TITLE
Newly installed Fedora template is not getting updates right after install

### ISSUE THREAD

**Issue by deeplow** [freedomofpress/securedrop-workstation#1166]
* [ ] I have searched for duplicates or related issues

## Description

Due to [the wrong variable](https://github.com/freedomofpress/securedrop-workstation/blob/main/securedrop_salt/sd-sys-vms.sls#L35) `fedora-40` was being updated instead of the newly fetched `fedora-40-xfce`. `fedora-40` does not exist in default systems and the salt updater was silently failing.

This should not affect current installations, since in 4.2.2 already came with fedora-40-xfce and thus no actual template upgrades have occurred.

## Steps to Reproduce

No need to reproduce. Visual inspection suffices.

## Expected Behavior

Downloaded template is updated immediately

## Actual Behavior

Silent failure.

**Comment by rocodes** [comment]
Thanks for the fix.  Just to share a bit more of our discussion re impact here on GitHub: 
Users are instructed to [apply system updates](https://workstation.securedrop.org/en/stable/admin/install/prepare.html#apply-updates-to-system-templates-estimated-wait-time-45-60-minutes) before provisioning SDW in order to ensure that system VMs are fully up to date. So this is an extra assurance measure relevant to provisioning (and should be a no-op under normal circumstance), but should of course be fixed. Thus our decision to treat this as part of the normal release cadence.

After provisioning, the built-in updater handles template updates and correctly updates fedora-40-xfce.
