### ISSUE TITLE
Assess security implications of multi-user access

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#153]
As discussed in #145, we must make a decision whether or not we want to support access by more than one journalist user to a physical workstation in the 0.1.0alpha release or shortly thereafter. To do so, we need to assess the security implications of multi-user access. Since Qubes itself is not a multi-user OS (every system-level user has full dom0 access), we should assume that we're not attempting to protect journalists from each other.

What we're interested in especially is whether there are specific mistakes or accidents that could increase the likelihood of exposing the system to security vulnerabilities in a context where more than one user has access, or that could lead to destruction of data, VMs or configurations.

**Comment by redshiftzero** [comment]
Excellent writeup @emkll, thank you for this. My .2 cents follow

> QubesOS does not claim to be a multi-user OS and that anything built on top will either not provide meaningful protections or will be difficult to implement in a way that is robust and maintainable.

Agree 100%.

Some background for the interested observer:

Right now, SecureDrop does not provide compartmentalization between journalists onboarded to the system. There is a global inbox, they share access to replies, and have a shared private key. Only trusted journalists from a single organization are onboarded. 

That said, there is desire for SecureDrop to evolve into a system that does have compartmentalization between at least teams and organizations (see: https://github.com/freedomofpress/securedrop/issues/2841), and maybe at an even more granular level (e.g. per-journalist keys as @emkll is mentioning). Each organization or journalist that wants to have meaningful separation between other users of the SecureDrop shares a security domain. In this model, there may be inter-organization or inter-journalist competition. There may be sensitive matters discussed in one organization that should not be available to another. In such a system, sharing a single user account on a single workstation is not appropriate, especially when that single user account has root/dom0 capabilities. 

We do need to consider this as we don't want to box ourselves into a development corner where we feel like we need to try to strap on true multi-user functionality to this system. 

## Short-term

But in the short term, there is a single security domain and if we want to allow users to use the workstation in a kiosk style, we could implement a lightweight mechanism for signing in to the client. These users would share VMs. This _would not provide any meaningful separation between journalist's activity_ and would simply serve to provide useful tracking of who did/who saw what for news organizations. In this situation, we would need to be clear to users of a single Qubes workstation that:

1. Your SecureDrop activity is always visible to other SecureDrop journalists if they wish to view it (no journalist-specific information should be stored on the workstation, so it mitigates the DATA1 risk where journalist-specific info is stored in the workstation).
2. Mistakes can impact other SecureDrop journalists (note: this does not mitigate SYSTEM1 or SYSTEM2). 
3. If users want to have private notes or want to customize their Qubes workstation (i.e. to add a Signal AppVM or other) etc., then they must get a separate workstation for their SecureDrop activity. These users are probably using SecureDrop a lot anyway, so this should not be an unreasonable ask. 

To partially mitigate AUDIT1, we could log journalist logins/logouts in the client. We'd have to correlate activity across VMs in order to determine which journalists did what. 

## Medium-term

In the medium-term view where we do have multiple security domains among SecureDrop journalists using a particular instance, we must have users from each security domain use a separate workstation. Indeed, most organizations that want many groups onboarded may want this anyway, e.g. a media conglomerate with multiple local newspapers across the US would need (at least) one workstation per local newsroom regardless, so this also should not be an unreasonable ask. 

Thoughts welcome on this

**Comment by eloquence** [comment]
Thanks much for the thorough analysis! I think framing this in terms of security domains really sharpens our thinking on it and also enables us to speak to news organizations about it using consistent language.

> if we want to allow users to use the workstation in a kiosk style, we could implement a lightweight mechanism for signing in to the client. 

What do you have in mind? One possible workflow (ultimate UX aside) that I can think of is a tabbed login screen.

```
__CONNECT TO SERVER__Work offline_

Username: [ Username  ] 
Password: [ Password  ] 
Code:     [ Code      ]

[ Login ]
```

```
_Connect to server___WORK OFFLINE__

Username: [ ^ Username ] 

[ Login ]
```

Excuse the crude ASCII art, the idea here is that if you choose "work offline", you would just have to select one of the users known to the workstation. You wouldn't be able to type an arbitrary name -- this would be a dropdown.

**Comment by ninavizz** [comment]
@ninavizz cc'ing myself fwiw

**Comment by eloquence** [comment]
I'm closing this issue as the assessment part is technically done, at least for now; we still need to take this information and make a decision, which is tracked in #145.
