### ISSUE TITLE
Create securedrop-workstation TemplateVM

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#156]
All AppVMs used by the Workstation should be based on Debian 9, along with a grsecurity-patched kernel built specifically for use in Qubes. We can call this template `securedrop-workstation-template`, and use it as the base for all VMs. A brief checklist of desired attributes:

* [x] Derived from `debian-9` template
* [x] Runs grsecurity-patched kernel
* [x] Virt mode set to HVM (required to run custom kernel)
* [x] Installs updates via FPF-controlled repository (apt-test-qubes)

The MVP implementation can use the existing config scripts to add the FPF apt-test repo pubkey and pull in the grsecurity-patched kernel. Ultimately, we should consider hosting an RPM to be installed in dom0, so that development environments for the Workstation are not contaminated by customizations to the `debian-9` template, which was discovered to complicate partial review of #155.

**Comment by joshuathayer** [comment]
To satisfy this issue, do we intend to use Salt to build and configure the template (before building RPMs)?

**Comment by emkll** [comment]
@joshuathayer : Some of this work has already be done, using the qubes-builder in https://github.com/freedomofpress/qubes-template-securedrop-workstation, which is very heavily inspired by the way Whonix builds their templates: https://github.com/adrelanos/qubes-template-whonix . At a high level, it works by building the Debian-9 template, and running script prior to packaging that installs packages and configures the kernel. You can try building your own template locally by following the Building the Templates section in the readme of this repo.

In those templates, 2 debian packages should be installed, both from an fpf-controlled apt-repo, so that they can be updated:
`securedrop-workstation-grsec`: Which is a metapackage that will pull in the latest workstation kernel (this is already done - https://github.com/freedomofpress/securedrop-workstation/tree/master/builder/packages/securedrop-workstation-grsec/debian)
`securedrop-workstation-config`: Pulls in the most basic configurations or dependencies for the base template. (wip here: https://github.com/freedomofpress/securedrop-debian-packaging/tree/securedrop-workstation-config-metapackage)

Once templates are baked with those two packages, they can be reliably updated via apt and the packages we control (kernel and config).

Since most of that I propose we use the above as a base template for all workstation VMs, and use salt to build and configure other templates during the install phase of the workstation. Does this approach make sense?

**Comment by ninavizz** [comment]
Question: is it the goal of this Qube to ONLY run the SecureDrop client (as a GUI element accessible to users)?

**Comment by eloquence** [comment]
@ninavizz This issue describes the creation a template from which various qubes (aka AppVMs - see https://www.qubes-os.org/doc/glossary/) would ultimately be instantiated. One of these would run the client, others will handle other parts of the process, such as connecting to the SecureDrop server. What's at the heart of your question? I suggest we discuss a bit more outside of the scope of this ticket as needed to ensure this is the right ticket for follow-up.

**Comment by ninavizz** [comment]
Taking q's to Gitter; gist = concerns w/ Qubes standards for nerdy audience, that I'd like to smooth out as much as possible for our users. Will be pinging Gitter with this, probs this eve or Monday. Need to focus on other stuff atm. Forgive my distraction, carry on! :)
