### ISSUE TITLE
Validate onion URLs before provisioning

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-workstation#240]
The `sd-whonix` VM will fail to start the `tor` process if the onion address is malformed.

**Comment by eloquence** [comment]
Is this still occurring, and if so, does it cause `make all` to hang when it does?

**Comment by redshiftzero** [comment]
also we should validate the auth cookie (cc #321 as we'll need to do the same for v3), the [expected format for v2](https://github.com/torproject/torspec/blob/master/rend-spec-v2.txt) is: 

> Valid onion addresses contain 16 characters in a-z2-7 plus
     ".onion", and valid auth cookies contain 22 characters in
     A-Za-z0-9+/

**Comment by creviera** [comment]
So I think `make all` used to hang here but now a Tor Config Check error window pops up with a message that says the onion address has the wrong format. I think validating the auth cookie would be an improvment, but also I wonder if there is a better error we could show that says the `config.json` file contains an error that points to the malformed json value?

**Comment by conorsch** [comment]
> we'll need to do the same for v3

Nearest I can figure for the v3 validation options is:

* v3 Onion URL regex: `^[a-z2-7]{56}\.onion$`
* v3 Onion auth regex: `^[A-Z2-7]{52}$`

That's based on my read of https://github.com/torproject/torspec/blob/master/rend-spec-v3.txt. Since both values are base32-encoded, that's the target charset to match against, with a known length for each value, to boot. Will update #379 accordingly, now that #321 is resolved.
