### ISSUE TITLE
Consider disabling hyperthreading 

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#257]
Given recent disclosures around CPU-based speculative execution vulnerabilities [1,2,3, ...]  and the possibility of a user to open arbitrary submissions within virtual machines, we should reduce the likelihood and impact of these types of attacks. 
While some microcode mitigations are provided upstream, full mitigations require disabling hyperthreading. We should investigate the performance impact of such a change.

This can be documented for a user to change that setting at the BIOS level, or setting  `smt=off`in either `/boot/efi/EFI/qubes/xen.cfg` ior  `/etc/default/grub` in dom0. 

[1] : https://zombieloadattack.com/
[2]: https://mdsattacks.com/
[3]: https://www.intel.com/content/www/us/en/architecture-and-technology/l1tf.html

**Comment by redshiftzero** [comment]
For this reason hyperthreading is disabled by upstream Qubes: https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.13/xen.spec.in#L686-L697

Relevant upstream tickets: 
https://github.com/QubesOS/qubes-issues/issues/5039
https://github.com/QubesOS/qubes-issues/issues/4252

Since this was done upstream (R4.0.1), closing
