### ISSUE TITLE
Remove non securedrop-client entries from sd-svs app menus

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#258]
followup from https://github.com/freedomofpress/securedrop-workstation/issues/198:

> we have an icon for "securedrop-client" in the menu, but it's buried among the many other entries. To resolve this issue, let's update the app menu for sd-svs to contain only the relevant entry

**Comment by creviera** [comment]
Ah, I didn't realize we actually had a `SecrureDrop Client` app that could show up in the applications menu for `sd-svs`. Until this Issue is resolved, you have to go to the `VM->Qube Settings->Applications` and select the application you want to show from the `Available` column and move it to the `Selected` column.

**Comment by eloquence** [comment]
The app is now always launched via desktop icon and should in fact never be launched via the menu. Closing.
