### ISSUE TITLE
Update sys-* VM templates in unattended upgrades

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#262]
Fedora 28 is now end-of-life [0], AppVMs that use Fedora 26 template should be updated to a more recent release. We should use Fedora 29 now or wait for a stable Fedora 30 template.

[0] : https://fedoraproject.org/wiki/End_of_life

@emkll @conorsch

**Comment by emkll** [comment]
Qubes 4.0.1 ships with Fedora29 templates by default, so we should recommend users start provisioning their workstation from 4.0.1, so that should resolve the situation in the near term. 

However, per your link, it seems like Fedora releases are supported for ~1 year, so we should ensure we are in a position to upgrade and swap in those templates once Fedora29 becomes end-of-life.

We've swapped templates before in https://github.com/freedomofpress/securedrop-workstation/issues/122, but this might be a bit more complex since sys-net, sys-firewall and sys-usb use Fedora templates.

**Comment by redshiftzero** [comment]
Wasn't this done as part of #245? (see 4ce8023f4251ced53af22aee289c61133017f038)

**Comment by emkll** [comment]
#245 only downloads the templates and upgrades the packages within the template. It does not swap the templates for `sys-net`, `sys-usb` and `sys-firewall` VMs.

**Comment by conorsch** [comment]
> We should use Fedora 29 now

That ask was indeed accomplished in #245? / 4ce8023. 

> It does not swap the templates for sys-net, sys-usb and sys-firewall VMs.

That's still unimplemented, which poses a large problem for _automatic_ transition away from EOL templates. There's already logic upstream to enforce the "default templates" (see `sudo grep -rF default_template /srv/` in dom0), which we may be able to leverage. The challenge will be to update the TemplateVM settings the `sys-*` AppVMs, since changes are not permitting to running VMs:

```
[user@dom0 ~]$ qvm-prefs -s sys-firewall template debian-9
qvm-prefs: error: Cannot change template while qube is running
```

Resolving the problem of applying template changes to sys- VMs automatically is what this issue, or a replacement, should track.
