### ISSUE TITLE
Consider moving submission processing to a dispVM

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#27]
Our work to give the user an interface which updates as documents are being processed (and displays appropriate messages in error cases) necessarily leaks sensitive information- for example, an attacker who controls the sd-journalist VM could gain knowledge about the keys contained in the sd-gpg VM by attempting to process specially-generated submissions encrypted to candidate keys and observing successes or failures through the status update mechanism.

By sending the submissions to a disposable VM for processing and running the user interface from that VM, the sd-journalist VM would have no knowledge about processing status, but the user could still have a rich experience.

**Comment by eloquence** [comment]
Motioning to close this issue as it is very outdated; if we want to consider a major architectural change like this, we need to consider it in the context of the specifics of the current architecture and data flow.

**Comment by conorsch** [comment]
Seconded! Back when this ticket was opened, "sd-journalist" was a network-connected VM running Tor Browser. We've since switched to use the client application (https://github.com/freedomofpress/securedrop-client/), which runs without a network interface, using an isolated qrexec proxy to handle network calls to the servers. Which is quite close to what was suggested with:

> By sending the submissions to a disposable VM for processing and running the user interface from that VM

So, fine with closing.
