### ISSUE TITLE
Packaging securedrop export code

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#271]
We currently have logic in the `send-to-usb` script for exporting files to USB drives. We'll be adding more export logic as time goes on e.g. as we add support for printing and (eventually) other export options. We should consider how we'll be updating this logic: we can put files in place via salt in dom0, but a more robust approach would be taking the approach we use in the sd-proxy and sd-svs VMs, which is packaging up the code (in the `securedrop-proxy` and `securedrop-client` debian packages) and then just using salt to ensure that package is installed.

**Comment by emkll** [comment]
Since there are a lot of moving parts, tracking progress/status in this comment
- [x] https://github.com/freedomofpress/securedrop-export/pull/1 create securedrop-export repo and merge code into there
- [x] https://github.com/freedomofpress/securedrop-debian-packaging/pull/69: add packaging logic to securedrop-debian-packaging
- [x] https://github.com/freedomofpress/securedrop-export/pull/2: Add tests in CI + update_version.sh to support automatic packages 
- [ ] https://github.com/freedomofpress/securedrop-debian-packaging/pull/71: Provide CD for securedrop-export packages
- [ ] Packages uploaded to apt-test-qubes.freedom.press (if the above is merged, will be done automatically by daily cron)
- [ ]  #298 : securedrop-workstation remove of export logic and install securedrop-export package
