### ISSUE TITLE
Manage pax flags in securedrop-workstation-grsec or securedrop-workstation-config

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#272]
Currently the builder logic adds a pax flag to the paxctld.conf file in https://github.com/freedomofpress/qubes-template-securedrop-workstation/blob/master/securedrop-workstation/04_install_qubes_post.sh#L59

We also manage a paxctld.conf file for sd-svs-disp inhttps://github.com/freedomofpress/securedrop-debian-packaging/blob/master/securedrop-workstation-svs-disp/paxctld.conf.svsdisp

We should manage the paxctld.conf file for alll templates in either securedrop-workstation-grsec or securedrop-workstation-config to ensure they are applied to all templates and qubes.

**Comment by eloquence** [comment]
Was this fully resolved by https://github.com/freedomofpress/securedrop-debian-packaging/pull/190?

**Comment by zenmonkeykstop** [comment]
@legoktm can we close?

**Comment by legoktm** [comment]
No...the line is still there: https://github.com/freedomofpress/qubes-template-securedrop-workstation/blob/b81c27fd8476b6fdadc5433a252d2109307adf0d/securedrop-workstation/04_install_qubes_post.sh#L64

Should be a quick PR.

**Comment by legoktm** [comment]
OK so,
1. This line doesn't actually make it into the running VMs because the paxctld.conf installed by securedrop-workstation-config clobbers it
2. `/usr/lib/gnome-terminal/gnome-terminal-server` no longer exists, it's now at `/usr/libexec/gnome-terminal-server`
3. In `sd-app`, running `systemctl --user status gnome-terminal-server` shows that it's running fine and given that I'm executing that in a gnome-terminal instance, it really just works.

So I'm going to submit a PR that removes it and doesn't add it anywhere else.
