### ISSUE TITLE
`make clean` error

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#286]
## Description

When running `make clean` in `Dom0` I see `Error: No packages marked for removal.`

#### STR
1. from `sd-dev` pull the latest changes from `master` branch
2. from `Dom0`, set the env vars needed for `make clone`
3. `make clone`
4. cd into cloned repo
5. update config.json with the correct server info
6. `make clean`

#### Expected output
```
Destroying VM 'sd-gpg'. . . OK
Destroying VM 'sd-proxy'. . . (absent)
.
.
.
Destroying VM 'sd-export-template'. . . OK
Purging Salt config. . . 
sudo dnf -y -q remove securedrop-workstation-dom0-config || true
sudo rm -f /usr/bin/securedrop-update \
           /etc/cron.daily/securedrop-update-cron
```

#### Actual output
```
Destroying VM 'sd-gpg'. . . OK
Destroying VM 'sd-proxy'. . . (absent)
.
.
.
Destroying VM 'sd-export-template'. . . OK
Purging Salt config. . . 
sudo dnf -y -q remove securedrop-workstation-dom0-config || true
Error: No packages marked for removal.
sudo rm -f /usr/bin/securedrop-update \
           /etc/cron.daily/securedrop-update-cron
```

**Comment by creviera** [comment]
Sometimes the output also contains:
```
qvm-kill: error: no such domain: 'sd-export-usb'
usage: ...
qvm-usb: error: no such domain: 'sd-export-usb'
```

**Comment by emkll** [comment]
I think those messages are "expected" and don't necessarily mean the clean operation has failed: What is important to know if the operation has failed or not is the return code of the `make` target. It is definitely counter-intuitive, and due to poor error handling in the Makefile:

* https://github.com/freedomofpress/securedrop-workstation/blob/2c1b543f62ca1232f31b5cb964c9621eca1eee8f/Makefile#L91
* https://github.com/freedomofpress/securedrop-workstation/blob/2c1b543f62ca1232f31b5cb964c9621eca1eee8f/Makefile#L96

**Comment by creviera** [comment]
Leaving this one open until one of us improves the output then. Thanks!
