### ISSUE TITLE
Change qubes-rpc policies to refer to the SVS VM by tag rather than name, to support development client VMs

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#288]
Currently, the only VM in the SD workstation that can be used with the client is `sd-svs` - this is enforced by qubes-rpc policies. This is appropriate for a production environment but less useful in development, as in order to work on a checked-out copy of the client code a dev must either:
1) enable networking on sd-svs, which breaks the securedrop-workstation security model,
2) copy changes from a dev VM to sd-svs, which is tedious
3) hand-bomb changes to qubes-rpc policy files, which is error-prone

One alternative would be to create a tag, `sd-client`, say, and use that in qubes-rpc policies in place of the `sd-svs` name. In a production system (and in the securedrop-workstation setup), `sd-svs` would be the only VM with that tag, but other VMs could be given the same tag for development purposes.

**Comment by creviera** [comment]
if you want a story for the development use case: https://github.com/freedomofpress/securedrop-workstation/issues/284

**Comment by creviera** [comment]
A couple tips Mickael shared with me today to make developing in Qubes easier:
* Use the same submission key across test servers (SF, home, and staging)
* Organize your key and config file copies in Dom0's home directory in a folder named after the server it is for, e.g. `~/sf` -> `~/sf/sd-journalist.sec`, `~/sf/config.json`, `~/staging` -> `~/staging/sd-journalist.sec`, `~/sf/config.json`, etc. Then you can copy them directly over the files saved in `~/securedrop-workstation` before you `make all`

**Comment by emkll** [comment]
This is a good idea: it would definitely save a little bit of time after each rebuild. As long as we have tests in place to confirm the presence of a "good" policy, which we do, I think this would be helpful for all developers. 
An added benefit would be more reliable testing: current tests for the RPC policies are definitely quite brittle, and would be best to have simple policies and test memberships via the prefs in the vm tests.

**Comment by conorsch** [comment]
The tag-based approach is a great solution to permit developers to write Client code in e.g. `sd-dev`, and open submissions in DispVMs directly from the Client interface. There's a separate problem in rotating connection details easily (see #284), but we can still provide a tighter feedback loop on client dev when connecting to the local server containers from the freedomofpress/securedrop repo's `make dev`. 

In order to support the tags, we'll need to clean up the packaging logic for `securedrop-client`, moving the files such as mimetype handlers out of the securedrop-workstation repo, and into the securedrop-client repo, much as we've done with securedrop-export (#271).
