### ISSUE TITLE
sd-proxy not getting installed in sd-proxy AppVM

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#325]
Several people on recent `make all` runs have reported not having `sd-proxy` installed in the `sd-proxy` AppVM. 

This ticket is both for awareness for people that are trying to provision for the first time but can't log in - ensure that you are installing the `securedrop-proxy` package in the `sd-proxy` AppVM (package name is `securedrop-proxy`, the command it exposes is `sd-proxy`) and to remind us that we should investigate what's going on here.

**Comment by emkll** [comment]
This happened to me, initial investigation is as follows:
- The command for installing the [sd-proxy package](https://github.com/freedomofpress/securedrop-workstation/blob/master/dom0/sd-proxy-template-files.sls#L44:L49) requires  `fpf-apt-test-repo`.
- Inside `fpf-apt-test-repo`,  the [disable-whonix-14-repositories-{onion,clearnet}](https://github.com/freedomofpress/securedrop-workstation/blob/master/dom0/fpf-apt-test-repo.sls#L48:L66) tasks are not set to run *before* the package update task nor the [install-python-apt-for-repo-config](https://github.com/freedomofpress/securedrop-workstation/blob/master/dom0/fpf-apt-test-repo.sls#L20:L25) task required to get the apt sources to work. As a result, the FPF apt repo does not get set up on the first run. 

Adding a condition to the `install-python-apt-for-repo-config` to require `disable-whonix-14-repositories-{onion,clearnet}` should resolve.
Otherwise, the upgrade to whonix-15 templates will definitely resolve (see #300  )

**Comment by redshiftzero** [comment]
nice investigation! I guess for the sake of people provisioning in the next few days we should add the condition until we have buster support for sd-proxy (this should probably be the first buster package so we can at least get the whonix 15 migration done)
