### ISSUE TITLE
increase storage space on sd-svs and sd-log

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-workstation#348]
I'm not sure how much to increase the space to yet (we could do it dynamically based on how much disk space is free on the disk) but we should increase the space available for VMs that are likely to contain a lot of data: primarily I'm thinking sd-svs (and then probably next is sd-log #340). 

This can be done via the qubes admin API (https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-storage.html#qubes.storage.Storage) or `qvm-volume resize <volume> <size>`

**Comment by conorsch** [comment]
For `sd-svs`, the disk space is going to grow mostly in the "private" (i.e. `$HOME`) volume. For `sd-log`, judging by the WIP #340, it looks like the "private" volume is also what we'd want to grow.

Since the VMs have a 2GB partition, what about growing sd-svs to 10GB, and sd-log to 5GB, as a start?

**Comment by redshiftzero** [comment]
for a first pass that definitely seems reasonable to me, we can file a followup for increasing the space based on the size of the disk or making it admin-configurable
