### ISSUE TITLE
Investigate ways to assist end users with Tor connectivity issues

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#353]
We should investigate the behavior of the workstation when the user switches between networks or temporarily loses their network connection. What does it take to restore Tor connectivity? If VMs need to be manually restarted to speed up the creation of Tor circuits, should we provide a simple helper script to accomplish this?

**Comment by ninavizz** [comment]
This is what the "Troubleshoot" window being open'able from the messaging was drafted to provide (unless you mean a code-script hidden from users, hence this ticket being in the Workstation repo). :)

https://invis.io/KXS6I4C4QA2

**Comment by eloquence** [comment]
We have a [troubleshooting guide](https://workstation.securedrop.org/en/latest/admin/troubleshooting_connection.html) now (screenshots TK), will be poking more at interactive in-client guidance post-beta.

**Comment by eloquence** [comment]
Any such troubleshooting tips would live in the client, so closing this issue.

**Comment by deeplow** [comment]
Re opening as we've received feedback that this is still a problem. Especially regarding the ergonomics of fixing a Tor connectivity issue currently.

For context, since this was last visited we've removed the need for Whonix, which left a gap in terms of tooling to restart Tor, as noted in the issue where we coordinated that removal: 

> **Additional work:** (out of scope for this issue)
> - make it easier to solve tor connection issues (now that we won't have Whonix's Tor Control panel)

 _Originally posted by @deeplow in [#456](https://github.com/freedomofpress/securedrop-workstation/issues/456#issuecomment-3053472782)_

**Comment by deeplow** [comment]
> Any such troubleshooting tips would live in the client, so closing this issue.

This reminded me that we could actually have a button in the client to restart Tor. This would fit under #1423. Since the app already communicates with `sd-proxy` we're not increasing the attack surface.

It could be a very simple RPC service like `securedrop.RestartTor` that does something as simple as:

```
#!/bin/sh
set -euo pipefail

sudo systemctl restart tor
curl --proxy socks5h://localhost:9150 \$(qubesdb-read /vm-config/SD_PROXY_ORIGIN) 
# on the previous command add a check if it was able to connect.
```

**Comment by deeplow** [comment]
Added this to next sprint candidates just so we consider this for triage as it shouldn't be too complicated.

**Comment by deeplow** [comment]
Tentatively assigning myself for this sprint to proprotype a minimal solution. But not actually move to implementation.
