### ISSUE TITLE
Missing concurrent.futures in sd-whonix

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-workstation#373]
While running `make all` I am getting the following error:

```
sd-whonix:
      ----------
      _error:
          Failed to return clean data
      retcode:
          0
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_62a99a_salt/salt-call", line 15, in <module>
              salt_call()
            File "/var/tmp/.root_62a99a_salt/py2/salt/scripts.py", line 395, in salt_call
              import salt.cli.call
            File "/var/tmp/.root_62a99a_salt/py2/salt/cli/call.py", line 5, in <module>
              import salt.utils.parsers
            File "/var/tmp/.root_62a99a_salt/py2/salt/utils/parsers.py", line 27, in <module>
              import salt.config as config
            File "/var/tmp/.root_62a99a_salt/py2/salt/config/__init__.py", line 98, in <module>
              _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
            File "/var/tmp/.root_62a99a_salt/py2/salt/config/__init__.py", line 88, in _gather_buffer_space
              import salt.grains.core
            File "/var/tmp/.root_62a99a_salt/py2/salt/grains/core.py", line 44, in <module>
              import salt.utils.dns
            File "/var/tmp/.root_62a99a_salt/py2/salt/utils/dns.py", line 32, in <module>
              import salt.modules.cmdmod
            File "/var/tmp/.root_62a99a_salt/py2/salt/modules/cmdmod.py", line 34, in <module>
              import salt.utils.templates
            File "/var/tmp/.root_62a99a_salt/py2/salt/utils/templates.py", line 32, in <module>
              import salt.utils.http
            File "/var/tmp/.root_62a99a_salt/py2/salt/utils/http.py", line 41, in <module>
              import salt.loader
            File "/var/tmp/.root_62a99a_salt/py2/salt/loader.py", line 28, in <module>
              import salt.utils.event
            File "/var/tmp/.root_62a99a_salt/py2/salt/utils/event.py", line 85, in <module>
              import salt.transport.ipc
            File "/var/tmp/.root_62a99a_salt/py2/salt/transport/ipc.py", line 21, in <module>
              from tornado.locks import Semaphore
            File "/var/tmp/.root_62a99a_salt/py2/tornado/locks.py", line 18, in <module>
              from concurrent.futures import CancelledError
          ImportError: No module named concurrent.futures
      stdout:
```

**Comment by conorsch** [comment]
I've removed the Whonix 15 template RPMs from my machine, in order to reproduce via a `make all` action. Will report results.

**Comment by conorsch** [comment]
Unable to reproduce. In dom0, I updated template settings so that the Whonix 15 templates weren't used at all, then ran:

```
sudo dnf remove qubes-template-whonix-{ws,gw}-15
make all
make test
```

And all tests were passing. Naturally the "make all" action took a long time, both due pull in the RPMs in dom0, and to update the Whonix-based templates over Tor. Still, there's clearly some divergence we haven't identified, given the different described behaviors here. For reference, I tested on latest master (e999834fed9f7b47a865f43b63801e91683b7a88).

**Comment by conorsch** [comment]
@redshiftzero suggested that differences in default management VMs may explain the inconsistent behavior we're observing. Here's what I have:

```
[user@dom0 ~]$ qvm-prefs $(qubes-prefs management_dispvm) template
fedora-29
```

@kushaldas Please let us know how your system is configured!

**Comment by emkll** [comment]
I installed Qubes 4.0.1 from scratch and ran `make all` and can reliably reproduce the error described by @kushaldas for all whonix-based templates and for securedrop-workstation-buster template. Note that in this case, despite the failure, `make all` exit code is 0.

On a related note, I also ran the securedrop-update script on this new install.The updater reports success (`OK`) on whonix/sd-* templates, but in reality, the update silently fails: manual update reveals packages need to be updated. It is likely the case that the same futures error is being returned but not being propagated.

`make clean`, and installing python-futures in securedrop-workstation-buster-template, whonix-ws-15 and whonix-gw-15 did resolve the issue locally (`make all` / `make test` passing).

I will examine the differences within /srv/salt between the two installs on Monday to try to shed some light on the divergence.

Regardless, I think the simplest path may be to simply install python-futures on all three templates at the start of the install process.

**Comment by emkll** [comment]
I compared both `/srv/` folders, there is no difference between those in the newer install (failed on python-futures) and those of the older install (does not fail on python-futures). I also checked the installed packages through `qubes-dom0-update --action=list` which returns the same installed package versions as https://github.com/freedomofpress/securedrop-workstation/pull/358#issuecomment-564650105

**Comment by redshiftzero** [comment]
here is my understanding thus far of what salt is doing in Qubes so that we can figure out how the drift can arise (i’m posting this so that someone can point out any errors, please do if you think i’m incorrect): 

1. `salt-minion` runs in dom0 (https://github.com/QubesOS/qubes-mgmt-salt/blob/4bde42588383d7287329b8a576ba66451345ef7c/qubessalt/__init__.py#L217) uses a modified version of `salt-call` in order to apply state changes to VMs (this is salt’s standalone minion mode: https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html#tutorial-standalone-minion)

2. For each VM where changes need to be applied, a management disp VM is started up based on `default-mgmt-dvm` template - `salt-ssh` is called from this management VM meaning that it is running under Python 2: https://github.com/QubesOS/qubes-mgmt-salt/blob/4bde42588383d7287329b8a576ba66451345ef7c/qubessalt/__init__.py#L165 which uses https://github.com/QubesOS/qubes-mgmt-salt/blob/ca06f944505953ef51ac0dcc229faccf9b49e599/qubes.SaltLinuxVM#L45. we're still using 

3. It temporarily overrides RPC policies for `Filecopy`, `VMShell`, and `VMRootShell` allowing data (the salt config https://github.com/QubesOS/qubes-mgmt-salt/blob/4bde42588383d7287329b8a576ba66451345ef7c/qubessalt/__init__.py#L159) and commands to flow _from_ the management disp VM to the target VM: https://github.com/QubesOS/qubes-mgmt-salt/blob/master/qubessalt/__init__.py#L277

4. salt commands run in the target VM - are these python? seems like these must be python, and the logic in the management VM is assuming that python concurrent.futures is installed, hence our issue

my suspicion is that there is divergence due to state not being the same in the management VM (which we can set on a per-VM basis in salt now which we might want to do in the future, and then ensure the management VM is included in the system updates) due to updates not being applied in fedora 29 which seems to be what most devs have as their default-mgmt-dvm

**Comment by emkll** [comment]
Based on my local testing , the table below shows the variations for salt packages default-mgmt-dvm templates in the environments I've tested in (only showing the packages that are differ across templates). 

Both fedora 29 and fedora-29 (updated at the start) require concurrent.futures, but fedora-30 does not. Setting the default-mgmt-dvm template to fedora30 resolves this issue. On my dev machine, I had changed the template manually, as I no longer have the fedora 29 template. This oversight may explain why it worked locally for me, but not for others, and not when I reinstalled the system.

It is still unclear to me what has changed in the fedora-30 template, but since f29 is out of date, we should handle the upgrade in place across the board.

| Fedora 29 | Fedora 29 - updated | Fedora 30|
|---------------|-----------------------------|-------------|
| qubes-mgmt-salt-vm-connector.noarch4.0.13-1.fc29| qubes-mgmt-salt-vm-connector.noarch4.0.10-1.fc29|qubes-mgmt-salt-vm-connector.noarch4.0.10-1.fc30|
| salt.noarch2018.3.2-5.fc29 | salt.noarch2019.2.0-1.fc29| salt.noarch2019.2.0-1.fc30|
| salt-ssh.noarch2018.3.2-5.fc29 | salt-ssh.noarch2019.2.0-1.fc29|salt-ssh.noarch2019.2.0-1.fc29|
