### ISSUE TITLE
whonix-{ws,gw} templates are not updated by securedrop-update cron

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#374]
Initially discovered by @kushaldas  in conjunction with #373 

This is because the Whonix VMs do not have the sd-workstation tag applied to them, see https://github.com/freedomofpress/securedrop-workstation/blob/e999834fed9f7b47a865f43b63801e91683b7a88/dom0/securedrop-update#L35

This causes two issues:

- sys-whonix, the updateVM used for all whonix template, does not have patches applied
- this increases provisioning and update times for sd-whonix and sd-proxy templates.

**Comment by conorsch** [comment]
Let's add a new tag. The `sd-workstation` tag is useful for identifying machines that would not otherwise exist if SDW weren't installed. For machines like `sys-whonix`, that's not the right tag. Suggestions:

* `sd-workstation-qubes`
* `sd-workstation-updates`

Then we target the cron updates with the union of both sets of tags. (It'll be far easier to do that in Python than bash, but we'll update as we go.)
