### ISSUE TITLE
Give good error feedback.

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#4]
When bad things happen, the user should know about it. Scripts should be able to use PyQT to open nice error dialogs when things go awry.

**Comment by redshiftzero** [comment]
Totally - one thing that we should have a nice PyQT dialog for is when the user is running low on memory - it's pretty easy to have your DispVMs hog all your memory when opening a few different documents.

**Comment by garrettr** [comment]
>  it's pretty easy to have your DispVMs hog all your memory when opening a few different documents.

Just a thought—you might be able to balance this concern by creating dedicated DispVM's per-source, instead of per-document (assuming that is possible, I think it might only be possible in Qubes 4.x). I think the security risk of opening all of a given source's submissions in a dedicated VM is neglible, and the memory savings could be significant.

**Comment by redshiftzero** [comment]
Implemented in #40
