### ISSUE TITLE
Start updater at boot, remove existing svs-disp backgound updater

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#415]
In https://github.com/freedomofpress/securedrop-workstation/pull/396, we have introduced a launcher to provide a way for users to control the update process. We would like the checks to happen as soon as the system boots to desktop.

We should re-use the autostart logic provided in [1] by replacing the background dispvm template update script (securedrop-login) by the QT application introduced in #396  

[1] https://github.com/freedomofpress/securedrop-workstation/pull/355/files#diff-19fc9e35327834b65d0d380e0da1a89bR19

**Comment by eloquence** [comment]
This could be split into two iterations:
-first iteration: replace `securedrop-login` as described
-second iteration: ensure that only one updater can be launched

**Comment by eloquence** [comment]
Regarding launching the preflight updater upon login, I admit to being somewhat ambivalent. Having two dueling paths to launch the app (login & desktop icon) could be confusing, and having the client login window pop up in every session feels a bit constraining for future use cases that may be independent of the client app. 

That said, since it's best to ensure that the workstation is up-to-date regardless of what the user does with it, I agree this is the way to go at this time. Adding the first two iterations to the sprint.

**Comment by eloquence** [comment]
> third iteration: ensure that only one updater can be launched

This was actually done in #445.
