### ISSUE TITLE
Template logs are their corresponding AppVMs

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#476]
This will make debugging updates more difficult, and will make it difficult to distinguish. 

Ideally, we would want to detect the VM based on the qrexec call. @kushaldas , is there a way we can detect the *source* of the ? Otherwise a compromised VM could spoof log source.

If we cannot detect source VM based on qrexec call, we should consider the following:
Replace `vmname` context in the configuration step to the that of the template [1] the and for AppVMs use the strategy used in `sd-whonix` via rc.local[2]

[1] https://github.com/freedomofpress/securedrop-workstation/blob/c54d5dd36dee6a3f6110789152ef63a577cdc1eb/dom0/sd-devices-files.sls#L36
[2] https://github.com/freedomofpress/securedrop-workstation/blob/c54d5dd36dee6a3f6110789152ef63a577cdc1eb/dom0/sd-whonix-rsyslog-enable.sls#L27

**Comment by kushaldas** [comment]
We should follow the [2] like `sd-whonix` in all VMs.

**Comment by conorsch** [comment]
Another option is to use the hostname reported by the logclient machine. That'll clearly distinguish between Template & AppVMs, as well as allow us to delete a considerable amount of configuration logic. Example of inferring hostname: https://github.com/freedomofpress/securedrop-log/compare/infer-hostname

The problem of "a compromised AppVM can claim to be a differently named VM" is a separate issue, and one I don't think we should try hard to solve for the pilot, where logging will be most useful for debugging application components. When we try to resolve the masquerade problem, we should consider using dom0 to aggregate and store the logs, since dom0 _already_ stores all syslog for each VM, with unique names for Template & AppVMs. See related comment https://github.com/freedomofpress/securedrop-workstation/issues/463#issuecomment-592259333
