### ISSUE TITLE
Run qvm-sync-appmenus on AppVMs

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop-workstation#520]
Initially reported by @zenmonkeykstop 

We run `qvm-sync-appmenus` only twice, and only for two TemplateVMs. 
* https://github.com/freedomofpress/securedrop-workstation/blob/f2afb1255af55cd2ba50937ef2398237938b0f8f/dom0/sd-app.sls#L60
* https://github.com/freedomofpress/securedrop-workstation/blob/f2afb1255af55cd2ba50937ef2398237938b0f8f/dom0/sd-devices.sls#L48

We should consider running this command for AppVMs for which we expect users to navigate to (for example, sd-whonix for anon connection wizard and sd-export for gnome-disks).

It may be best to run it as a separate salt target, so that we can run it during an install but also as part of the dom0 provisioning if required (it requires the VM to be powered on prior to running that command)

Related: #365

**Comment by zenmonkeykstop** [comment]
It's unclear whether we should be making appmenus available at all in most cases. We should decide what if any menu items are required.

**Comment by zenmonkeykstop** [comment]
See also https://github.com/freedomofpress/securedrop-workstation/pull/857 which may resolve this issue.

**Comment by legoktm** [comment]
> See also #857 which may resolve this issue.

We decided (and implemented) that all the VMs should be hidden except sd-devices and sd-whonix, which have tools that users may need to manually start. We already run qvm-sync-appmenus for the small and large templates, we just need to do it for whonix. And then set menu items for those two VMs specifically. 

I'm picking this up now since I need to do it to address https://github.com/freedomofpress/securedrop-workstation/issues/1109, which points out that we've regressed in the menu items for sd-devices.
