### ISSUE TITLE
Add --install as synonym for --apply to securedrop-admin

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#537]
It's natural to want to type `securedrop-admin --install`, especially for folks used to the Tails `securedrop-admin install` workflow . We should IMO support it as a synonym.

**Comment by conorsch** [comment]
No concerns with the alias. Tempted also to convert to a subcommand: `securedrop-admin install`, rather than `securedrop-admin --install`, same as the Tails tool. There's potential for confusion already, given that the "securedrop-admin" tool in Tails manages the servers, and the "securedrop-admin" tool in Qubes dom0 manages the VM components, but I don't really see that as a blocker here.

**Comment by zenmonkeykstop** [comment]
This is probably unnecessary, a. CLI works as is and b. a GUI installer may be in the pipeline. Closing.
