### ISSUE TITLE
Enable securedrop staging to run as a Qube

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#58]
Currently, securedrop-workstation requires running a staging SecureDrop instance on a separate machine (under Vagrant). It would be very helpful to be able to run a staging instance from the machine where securedrop-workstation is being developed.

Research what changes may need to be made to https://github.com/freedomofpress/securedrop to allow it to be run in a Qubes VM and develop a process for deploying it.

**Comment by eloquence** [comment]
An alternative stopgap measure would be for FPF to provision VMs that developers can connect to. We should compare relative effort required -- if it's fairly straightforward to provision directly within Qubes, that does seem like the ideal approach. Adding to near-term backlog for SD dev to do some research here, since this will become pressing as workstation development picks up steam.

**Comment by conorsch** [comment]
Let's certainly evaluate the effort involved in both centralized VM hosting and full Qubes support for Ubuntu SD VMs. The latter would certainly be superior, in that _anyone_ running Qubes would still use the SD dev env, without needing to be onboarded to a VM management service. 

Note that the Qubes support is complicated by the use of Ubuntu specifically for the SD VMs—see here for a brief overview of the work involved: https://www.qubes-os.org/doc/templates/ubuntu/

**Comment by eloquence** [comment]
Running as a Qube with template VM turned out to not be very viable due to lack of official support for Ubuntu Qubes VMs and the complexity of the manual build process.

We're targeting the use of [HVMs](https://www.qubes-os.org/doc/hvm/) instead. To minimize confusion, filing a separate issue for that and closing this one.
