### ISSUE TITLE
Add "Remind me later", "Update now" options to sdw-notify.py

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#595]
The notifier script currently just shows a warning/reminder that it's time to update, and will come back on the dot every hour if you defer the update. It would be good to:

1. Give the user the option to launch the updater from the notification
2. Give the user the option to silence the notification for a limited time (e.g., 8 hours).

The "Update now" option should detect if `sd-app` is currently running and, if so, show a warning that it will be shut down as part of the update.

We should decide on the full UX before implementation. Many UIs do this with "Remind me later", "Update now" type actions (e.g., the [Ubuntu updater](https://149366088.v2.pressablecdn.com/wp-content/uploads/2013/04/software-updater.jpg)).

**Comment by ninavizz** [comment]
Yup. This is a standard pattern on Macs and Windows boxes, too.

**Comment by eloquence** [comment]
@zenmonkeykstop pointed out that we may be able to use built-in system tooling for this notification. Two tools that are commonly used in Qubes already are `notify-send` and `zenity`. From what I can tell, `notify-send` is not a good fit for our use case, as it does not allow for interactive notifications.

`zenity`, on the other hand, is built for basic dialogs. Here's an example of a `dom0` dialog created with `zenity`:

![zenity](https://user-images.githubusercontent.com/213636/140265254-96c4a253-f09a-4714-9c44-2d6ee9a061a7.png)

The `zenity` command for this dialog is:

```
zenity --width 600 --question --cancel-label "Remind me later" --ok-label "Update now" --title "Security check recommended" --text "The computer has not been checked for security updates recently. Would you like to check for updates now?"
```

`zenity` also has a notification feature, but it also seems too limited (it does show an inline "Do default action" button but it doesn't appear to be customizable). But a dialog similar to the above may be sufficient for our use case.

**Comment by gonzalo-bulnes** [comment]
Nitpicking / my two cents: is it the computer that's "being checked", or is it the computer that does the checking? When I first glanced over the message I thought: "Wait what do you want to do to my computer?" and I believe it's because if the computer is the object of the check then it is not said who checks the computer... 

The second sentence says that the user checks, which sounds fine, and I'd otherwise, expect the computer to perform automated checks on behalf of the user (or as the user _agent_). (I'm saying I don't expect an un-named entity to be performing automated checks _of_ the computer, am I making any sense?) In short, I'd have expected to read: `The computer as not checked for security updates recently. Would you like to check to updates now?`

**Comment by creviera** [comment]
> The computer has not checked for security updates recently. Would you like to check for updates now?

+1 to this suggestion

**Comment by creviera** [comment]
@rocodes looking forward to your involvement on the secureDrop worksation next week! this might be a good issue for you to chime in on given your interest in making updater improvements.

**Comment by ninavizz** [comment]
+1'ing not using the Qubes window. It also appears strange and is inconsistent from the Preflight Updater. In Figma there's some suggestions. 

Our users are not native Linux users, so its important we not burden them with remembering all of the unique ways their Qubes machine is different from their Mac. "That looks different" is their primary means to identify malware. 

ALSO, YAY FOR RO!!

**Comment by eloquence** [comment]
@ninavizz 
> +1'ing not using the Qubes window. I

What are you responding to here? What do you mean with "the Qubes window"?

**Comment by ninavizz** [comment]
@eloquence What you spoke to as a Zenity window. Sorry, not wanting to create distractive noise. Just a frustrating balance—provide users experience that make sense to them, or force them into Linux conventions where things all look slightly (or radically) different from each other.

**Comment by rocodes** [comment]
I'm working on this improvement and will put up a draft PR shortly. I've used QTMessageBox instead of Zenity as per @ninavizz's request; here are some screenshots of the dialogs in their current form for Nina's ease of inspection :)  The second one is what's shown when `sd-app` is running.
 
![check_for_updates](https://user-images.githubusercontent.com/22777700/143301765-38044e9b-f15f-4a29-ac44-42b11b1e25f0.png)
![check_for_updates_sd_app_running](https://user-images.githubusercontent.com/22777700/143301768-303b7bb3-48bd-4cf6-a6d1-6ed12eb46c65.png)

My only question is about the "defer reminders" part. It's got potential to make things a _teeny_ bit complicated (like, when to respect the `GRACE_PERIOD` and when to respect the `DEFERRAL_PERIOD`? If we have a flag file that says "this user has deferred updates, don't bug them for a bit", we have to add a little extra logic to make sure not to bug the user during the deferral period, and then make sure to stop repressing the notifications after the deferral period so the user definitely gets update warnings).  

I don't think it's necessarily too hard, but since it is a little bit of extra logic, I just want to make sure we all agree that a special deferral window is beneficial before I go ahead and finish that part. (Otherwise, the deferral window is just the window in between when the user dismisses this dialog and when the cron job fires, which is roughly hourly). 

Hope that makes sense, comments welcome :)

**Comment by rocodes** [comment]
(Also, @ninavizz, I've not spent a lot of time customizing the look and feel of the window, but I'm happy to check in about that to make sure everything looks consistent)

**Comment by ninavizz** [comment]
@rocodes Those are GREAT, Ro! 

Today's experience of thwacking an "OK" button instead of a "Ok, do this now" or "Nah, nag me later" button is so poor when done day after day—and what you did above, alone, is a great improvement. 

The only aesthetic concerns I have are with the wordsmithing; not the appearance. 
1. Beginning a sentence with "The" or "This" is an anti-pattern in UI copywriting. Always start the sentence with what you're speaking to, or a verb. The goal of UI text is to inform behavior, not to provide a "reading experience." If that makes sense. 
2. Asking a question and then throwing-up a warning feels jarring. 
3. I'd also like the user to know that this is a dialog from the SecureDrop updater, and not the "explody icon" updater.

"Recently" is also throwing me off, because in the minds of regular folks "yesterday" is recently.

Below is what I'd put in my wireframes. The sentence immediately begins with the word "Security" to get the user's brain centered on the what and why. Much as I dislike the word "recently," users have been trained that the preflight updater needs to run daily—so speaking to SecureDrop in the text of the window, can also help them connect those concepts.

Thank you for including the screenshot for me! <3 Someday I'll learn how to check-out builds and run things, myself. Someday. I'll also own a rainbow-painted Porsche and drive a Mercedes Benz, too. ;)

<img width="545" alt="Screen Shot 2021-11-24 at 11 47 12 AM" src="https://user-images.githubusercontent.com/8262612/143304229-ec7b6b94-5347-45e8-b4c6-49608cea4a26.png">

**Comment by rocodes** [comment]
Ok, so it sounds like there's still some consensus needed around the wording--I was going roughly by what was discussed in the [comments above](https://github.com/freedomofpress/securedrop-workstation/issues/595#issuecomment-965719449), maybe we can work that out in the comments here. 

Also: at today's sdw developer hangout, we discussed the pros and cons of implementing a separate interval for "Remind me later", and we were thinking that introducing a new deferral window here may not be the highest priority. (If we do introduce one, there would be the 8-hour window, the 5-day cutoff for `notify-send`, the grace period, _and_ the deferral interval, and what we may want instead is to simplify the entire update story).     

@eloquence, mostly looking to you for some feedback here--would you be okay with not implementing a longer "Remind me later" interval for the time being?

**Comment by eloquence** [comment]
Yeah, totally. In fact I think we could change the cron job to run every two hours, which would make "later" indeed a bit later :)
