### ISSUE TITLE
Move securedrop-proxy mimetypes to package

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-workstation#615]
The mimetype associations added to the `sd-proxy` VM are currently configured via Salt, not via the `securedrop-proxy` deb package, or any other package. As we work on template consolidation (#471), we should remove those mimetypes from salt and update the symlink-targeting logic introduced in #605.

**Comment by emkll** [comment]
Currently, `sd-proxy` provides a basic Qt window that will be displayed when any file is opened, see: https://github.com/freedomofpress/securedrop-workstation/blob/56c86b1088deb8502ccfcc58b301a138297f59c3/sd-proxy/do-not-open-here

This behavior is what remained from past (pre 0.1.0) iterations, where the workstation relied on users downloading submissions and messages via Tor Browser and opening them manually.

Since we now use the SecureDrop client, to handle file and message management, it might make sense to use the most defensive mimetype handler by default, the same one as `sd-app`, in other words, opening in a Disposable, non-networked VM by default (`openindvm. desktop`)
