### ISSUE TITLE
Install `diceware` in the SDW templates for admin use

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#712]
Side note: we should be installing `diceware` in the SDW templates and instructing admins to use it.

_Originally posted by @conorsch in https://github.com/freedomofpress/securedrop-workstation-docs/pull/81#r645207725_

**Comment by eloquence** [comment]
As discussed in backlog review today, the `vault` VM based on `fedora-33` ships with KeePassXC (which we also recommend using in our docs). It includes diceware functionality (you have to select the "passphrase" tab instead of the "password" tab when generating a passphrase). So I think we can reasonably close this.
