### ISSUE TITLE
Release SecureDrop Workstation 0.6.0

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-workstation#760]
## Description

Time for a new release of the workstation to include the following changes:
* Check for network connection before running preflight updater ([#743](https://github.com/freedomofpress/securedrop-workstation/pull/743))
* Add option to launch updater from sdw-notify script ([#740](https://github.com/freedomofpress/securedrop-workstation/pull/740))

## Checklist

Following https://github.com/freedomofpress/securedrop-workstation/wiki/Building-securedrop-workstation-dom0-config-RPM-package...

* [x] Bump RPM version to 0.6.0: https://github.com/freedomofpress/securedrop-workstation/pull/761
* [x] Create signed tag for 0.6.0 - https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.6.0
* [x] Build RPM, sign with test key, submit to dev lfs repo (this is necessary to keep staging in sync even if we don't test separately) - https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/30
* [x] Resign RPM with prod key, submit to prod lfs repo
* [ ] Post-release check (run `make clean && make prod` to get the new package from the yum repo)

### Check for network connection before running preflight updater ([#743](https://github.com/freedomofpress/securedrop-workstation/pull/743))

Disconnect your computer from the internet.
- [ ] In dom0, run `python3 /opt/securedrop/launcher/sdw-launcher.py` and click "Apply Updates." Observe an immediate network failure error message.
- [ ] Reconnect to the internet and rerun the launcher script. Ensure you can successfully run the preflight updater.
- [ ] Ensure the above steps work with both ethernet and wireless connections.   

### Add option to launch updater from sdw-notify script ([#740](https://github.com/freedomofpress/securedrop-workstation/pull/740))

Ensure `sd-app` VM is shut down.
Edit the file in `dom0` called `~/.securedrop_launcher/sdw-last-updated` to change the date to a date >= 5 days ago.
Run `python3 /opt/securedrop/launcher/sdw-notify.py`:
- [ ] Notification appears with prompt to check for updates.
- [ ] No "**Warning:**" text is present in the notification
- [ ] The default selected button option is "Check for updates".
- [ ] Clicking "Remind me later" (or pressing the Esc key) closes the dialog window. Note the time.

Start `sd-app` vm via `qvm-start sd-app` in `dom0`. Wait for the notify prompt to reappear. ..

- [ ] The notify prompt appears again after a delay of t < 2 hours (The reminder runs every 2 hours on the even hours. The delay will depend on what time the user dismissed the dialog).
- [ ] This time, the "**Warning:**" text is present in the notification
- [ ] Clicking "Check for updates" launches the Preflight Updater.  
- [ ] The Preflight Updater can run updates successfully.
- [ ] No GTK warnings or other errors are generated or printed to the `dom0` console when the Preflight Updater is launched.

**Comment by eloquence** [comment]
### Check for network connection before running preflight updater ([#743](https://github.com/freedomofpress/securedrop-workstation/pull/743))

Disconnect your computer from the internet.
- [x] In dom0, run `python3 /opt/securedrop/launcher/sdw-launcher.py` and click "Apply Updates." Observe an immediate network failure error message.
- [x] Reconnect to the internet and rerun the launcher script. Ensure you can successfully run the preflight updater.
- [x] Ensure the above steps work with both ethernet and wireless connections.   

### Add option to launch updater from sdw-notify script ([#740](https://github.com/freedomofpress/securedrop-workstation/pull/740))

Ensure `sd-app` VM is shut down.
Edit the file in `dom0` called `~/.securedrop_launcher/sdw-last-updated` to change the date to a date >= 5 days ago.
Run `python3 /opt/securedrop/launcher/sdw-notify.py`:
- [x] Notification appears with prompt to check for updates.
- :x: No "**Warning:**" text is present in the notification
- [x] The default selected button option is "Check for updates".
- [x] Clicking "Remind me later" (or pressing the Esc key) closes the dialog window. Note the time.

However, I think the behavior is as expected: if sd-app is running, the warning text appears; it was running because I completed an update in the previous step. I'll let it run its course and confirm that the 2 hour delay works as expected.

**Comment by eloquence** [comment]
Start `sd-app` vm via `qvm-start sd-app` in `dom0`. Wait for the notify prompt to reappear. ..

- [x] The notify prompt appears again after a delay of t < 2 hours (The reminder runs every 2 hours on the even hours. The delay will depend on what time the user dismissed the dialog).
- [x] This time, the "**Warning:**" text is present in the notification
- [x] Clicking "Check for updates" launches the Preflight Updater.  
- [x] The Preflight Updater can run updates successfully.
- [x] No GTK warnings or other errors are generated or printed to the `dom0` console when the Preflight Updater is launched.

**Comment by conorsch** [comment]
I performed another round of final QA today. No surprises encountered, we're good to go.

### Check for network connection before running preflight updater ([#743](https://github.com/freedomofpress/securedrop-workstation/pull/743))

Disconnect your computer from the internet.
- [x] In dom0, run `python3 /opt/securedrop/launcher/sdw-launcher.py` and click "Apply Updates." Observe an immediate network failure error message.
- [x] Reconnect to the internet and rerun the launcher script. Ensure you can successfully run the preflight updater.
- [x] Ensure the above steps work with both ethernet and wireless connections.   

### Add option to launch updater from sdw-notify script ([#740](https://github.com/freedomofpress/securedrop-workstation/pull/740))

Ensure `sd-app` VM is shut down.
Edit the file in `dom0` called `~/.securedrop_launcher/sdw-last-updated` to change the date to a date >= 5 days ago.
Run `python3 /opt/securedrop/launcher/sdw-notify.py`:
- [x] Notification appears with prompt to check for updates.
- [x] No "**Warning:**" text is present in the notification
- [x] The default selected button option is "Check for updates".
- [x] Clicking "Remind me later" (or pressing the Esc key) closes the dialog window. Note the time.

Start `sd-app` vm via `qvm-start sd-app` in `dom0`. Wait for the notify prompt to reappear. ..

- [ ] The notify prompt appears again after a delay of t < 2 hours (The reminder runs every 2 hours on the even hours. The delay will depend on what time the user dismissed the dialog).
-  :orange_square: I skipped this portion of the test plan; however, i've been test-driving these changes for a while now, since I keep the latest HEAD of the repo installed locally, via make dev.
- [x] This time, the "**Warning:**" text is present in the notification
- [x] Clicking "Check for updates" launches the Preflight Updater.  
- [x] The Preflight Updater can run updates successfully.
- [ ] No GTK warnings or other errors are generated or printed to the `dom0` console when the Preflight Updater is launched.
  - :orange_square: Technically I did see one warning, related to https://github.com/freedomofpress/securedrop-workstation/issues/754, but that's not due to the updater changes, and only appear because I violated the "wait for the notify prompt to reappear" step above.

**Comment by creviera** [comment]
Whoops, sorry, closed this prematurely. We still have one more check to run `make prod` in order to pull down the latest workstation package and run the updater to ensure it works as expected.

**Comment by eloquence** [comment]
(Stepping through this real quick - uninstalling SDW, then installing 0.5.7 RPM and finally running updater to see if there are any issues getting to 0.6.0.)

**Comment by eloquence** [comment]
On my Qubes 4.0 system, the preflight updater did _not_ apply the available updates. Although the `--check-only` call in https://github.com/freedomofpress/securedrop-workstation/blob/9db541ea47cd9c8bc22d84daf0849f752c2663c0/launcher/sdw_updater_gui/Updater.py#L151 showed that updates are available, the updater interpreted the result as "No updates available for dom0". This could be an issue local to my system, or an upstream change in behavior. I'd appreciate if someone else can step through the same process above to verify.

Manually applying the update in dom0 worked fine and passed smoke tests.

**Comment by eloquence** [comment]
(This was done a while ago, we just didn't close it due to the dom0 update issue.)
