### ISSUE TITLE
Release RPM 0.6.2 with fedora-35 support

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#776]
This is a tracking issue for a point release with support for fedora-35.

* [ ] Bump RPM version to 0.6.1
* [ ] Create signed tag for 0.6.1
* [ ] Build RPM, sign with test key, submit to dev lfs repo 
* [ ] Re-test fedora-35 changes introduced in https://github.com/freedomofpress/securedrop-workstation/pull/774 (see below)
* [ ] Resign RPM with prod key, submit to prod lfs repo
* [ ] Post-release check (run `make clean && make prod` to get the new package from the yum repo)

## QA Test Plan
**Testing**
- Ensure your Qubes 4.0 workstation is set to a staging environment and that your sys-* VMs are using fedora-34
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [ ] Updater prompts for reboot
- [ ] System templates are switched to fedora-35
- [ ] Basic functionality (network connectivity, attaching/detaching devices via sys-usb) is working
- [ ] New Fedora-35 DVM is created and displays in appmenu; other fedora dispvms can still be opened
- [ ] `default-mgmt-dvm` is fedora-35, as are templates for sys-net, sys-usb, sys-firewall

**Comment by rocodes** [comment]
After discussion with @creviera, this release will be more like a hotfix release, targeting Qubes 4.0 only. We are going to avoid pulling in any of the Qubes 4.1 compatibility changes, which have already landed in `main`. 
Our plan is to:
- [x] create a separate branch based off of the last release tag, include the Fedora 35 template switch (cherry-picked from `main`) and the changelog and version update (https://github.com/freedomofpress/securedrop-workstation/tree/0.6.1-f35-base-template)
- [ ] Maintainer signs and pushes the 0.6.1 tag: https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.6.1
- [ ] Reviewer reviews signs with release key,  builds and release off of that branch, without merging branch into main (release mechanics as described above)
- [ ] Pull in the changelog commit to the next release of the workstation config RPM, to ensure an accurate changelog.

**Comment by creviera** [comment]
In case others are following along, we are using these docs for reference: https://github.com/freedomofpress/securedrop-workstation/wiki/Building-securedrop-workstation-dom0-config-RPM-package

**Comment by creviera** [comment]
Sorry @rocodes, changed plans while you were out to use an RC version number (which we didn't do as part of the 0.6.0 release https://github.com/freedomofpress/securedrop-workstation/issues/760)

**Comment by rocodes** [comment]
@creviera : I'm going to update the test plan to use the "Testing once templates have already landed" path in the initial issue, if that's okay!

**Comment by eloquence** [comment]
- [x] Updater prompts for reboot
- [x] System templates are switched to fedora-35
- [x] Basic functionality (network connectivity, attaching/detaching devices via sys-usb) is working
- [x] New Fedora-35 DVM is created and displays in appmenu; other fedora dispvms can still be opened
- [x] `default-mgmt-dvm` is fedora-35, as are templates for sys-net, sys-usb, sys-firewall

**Comment by rocodes** [comment]
## QA Test Plan
**Testing**
- Ensure your Qubes 4.0 workstation is set to a staging environment and that your sys-* VMs are using fedora-34
- Note: I had to install the fedora-35 template to successfully run the updater (but not switch over the system vms) because I had previously installed it, and I suspect there is an upstream bug there
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [:x:] Updater prompts for reboot (Not expected because f35 template was already installed?)
- [x] System templates are switched to fedora-35
- [x] Basic functionality (network connectivity, attaching/detaching devices via sys-usb) is working
- [:x:] New Fedora-35 DVM is created and displays in appmenu; other fedora dispvms can still be opened (DispVMs based on older templates still work, default-mgmt-dvm is fedora-35, but fedora-35-dvm was not created)
- [x] `default-mgmt-dvm` is fedora-35, as are templates for sys-net, sys-usb, sys-firewall

**Comment by cfm** [comment]
- Ensure your Qubes 4.0 workstation is set to a staging environment and that your sys-* VMs are using fedora-34
- Force a run of the updater with `/opt/securedrop/launcher/sdw-launcher.py --skip-delta 0`
- [ ] Updater prompts for reboot

*No, after first failed run (due to networking hiccup) that installs `fedora-35` and second successful run that does the rest; ticket TK*

- [x] System templates are switched to fedora-35
- [x] Basic functionality (network connectivity, attaching/detaching devices via sys-usb) is working
- [x] New Fedora-35 DVM is created and displays in appmenu; other fedora dispvms can still be opened
- [x] `default-mgmt-dvm` is fedora-35, as are templates for sys-net, sys-usb, sys-firewall

**Comment by rocodes** [comment]
(Updating for completeness: My QA results should not be a release-blocker, because they resulted from a state that pilot participants probably won't have entered, which is installing the f35 template manually and then uninstalling it. If anyone has done so, we can provide workaround steps, which would be to manually reinstall the template and then create a fedora-35-dvm).

**Comment by eloquence** [comment]
Due to use of an incorrect key, this RPM is being re-issued as 0.6.2; re-titled issue accordingly. I've confirmed smoke-test of the dev build at https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/33 by installing it using the pref-light updater in a Qubes 4.0 staging environment.

**Comment by eloquence** [comment]
This was completed on 2022-06-02, thanks all!
