### ISSUE TITLE
Extract launcher into a `securedrop-workstation-updater` repo/ package

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-workstation#808]
# Description

Both @rocodes and @eaon have mentioned wanting to move https://github.com/freedomofpress/securedrop-workstation/tree/main/launcher into its own repo and to package it separately. 

Opening this issue to capture conversation here.

Might be nice to pair this issue with https://github.com/freedomofpress/securedrop-workstation/issues/785

**Comment by eloquence** [comment]
Discussed a bit with @eaon today. A few early notes:
- As part of this change, it would be good to standardize the name of this tool throughout: `updater` or `launcher`.
- The launcher is currently installed in `/opt`; is there a good reason not to move at least the executable into `/usr/bin` (which is where the `securedrop-login` script already resides)?
- As part of that we may also want to drop the `.py` extension from the executable.
- `securedrop-login` script and the AutoStart `.desktop` file would have to be packaged within the RPM.
- The `sdw-notify` notifier script, if we keep it around (there are good reasons to check in on whether it actually adds value), would have to be packaged along with the updater. That might entail migrating from an `/etc/crontab` entry to a `systemd` service/timer, which could avoid help avoid ugly file substitutions in postinst.

**Comment by eaon** [comment]
Have been poking at this a bit. Here's where I'd go next:

1. Take the `securedrop-workstation` repo and [follow a similar filter-repo process](https://github.com/freedomofpress/securedrop/issues/5435#issuecomment-689882763) as `securedrop`/`securedrop-docs`. This implies that commit signatures will get lost in the process. They will continue to be verifiable in `securedrop-workstation` though, and the first commit in the new repo will get signed (which essentially means the entire history up to that commit is signed along with it)
1. Create a `sans-launcher` branch in `securedrop-workstation` that removes / moves / adds the necessary functionality (downloading the new package from our yum repo would have to be added to our dom0 🧂)
1. Create new `securedrop-updater` repo (where the name reflects the primary function of the code: enforce our update policy - rather than just launch the client from dom0).
1. In that new repo, go with pretty much all the changes summarised by @eloquence (including deferring the discussion whether the update notification is useful, and use a systemd based timer)

**Comment by gonzalo-bulnes** [comment]
I look forward to seeing that separate repo! (And I'd love to look further into the GUI aspects once the _updater_ code base is isolated. :tada: On that topic: I fully second your naming thoughts @eaon!)

**Comment by eaon** [comment]
Update on how this is going:

* The [`securedrop-updater`](https://github.com/freedomofpress/securedrop-updater/) repo exists now - the history of relevant files was preserved as best as possible with filter-repo
  * A systemd based notification timer to replace the crontab based notification (see also: relevant [systemd docs for user units](https://manpages.debian.org/bullseye/systemd/systemd.special.7.en.html#Special_Passive_User_Units)) has yet to be added, and would also need some :salt: updates to `securedrop-workstation`.
  * Builds are reproducible and lean on the work done by `securedrop-workstation` here
  * The repo layout is a little closer to `securedrop-client` (an attempt to standardise)
  * Executables get dropped into `/usr/bin`, Python packages into system `site-packages`, other files like `.desktop` files and icons also get dropped into the appropriate system directories
* With the `808-sans-launcher` branch / PR #831, the launcher code was removed and replaced with salt states that install a `securedrop-updater` rpm package after the workstation's yum repositories were added and enabled. This technically introduces a dependency that is enforced by SaltStack rather than the `.spec` file
  * Installing from scratch already works (if the `securedrop-updater` rpm was installed manually before running `sdw-admin --apply`) …
  * … however we will also need to trigger a migration for this because we need to of how file names changed. I believe this would be a good opportunity to revisit our :salt: based migration strategies (and we may want to look into how a better integration with `securedrop-updater` could make this even more robust in the future). This is a conversation I'd love to have with @rocodes and @gonzalo-bulnes next week.

**Comment by eaon** [comment]
This work is underway, we're aiming to [release SecureDrop Updater in mid February](https://github.com/freedomofpress/securedrop-updater/issues/13), shortly followed by a release of SecureDrop Workstation to integrate the separate package.

Here's what's left to do on the SecureDrop Workstation side of things. 

1. Merge [build containerization](https://github.com/freedomofpress/securedrop-workstation/pull/851) (not strictly necessary but it gets closer to aligning it with `securedrop-updater` in spirit
2. Remove launcher from the workstation repository (see: https://github.com/freedomofpress/securedrop-workstation/pull/831 which needs rebasing)
   * This bit will need testing as the updater will run while its files are being removed. If that breaks the updater we will need to ship the launcher one last time despite not using those files after that one installation
   * We don't ship .pyc files so we may want to do some more manual cleanup in `%post`
6. Add Salt states that download and install `securedrop-updater` from the repo we add (also handled by https://github.com/freedomofpress/securedrop-workstation/pull/831)
   * The way @eloquence and I read [UpdaterApp.py#L239](https://github.com/freedomofpress/securedrop-workstation/blob/main/launcher/sdw_updater_gui/UpdaterApp.py#L239) and [Updater.py#L372](https://github.com/freedomofpress/securedrop-workstation/blob/main/launcher/sdw_updater_gui/Updater.py#L372), dom0 will _always_ run the salt states during every updater run, which means we shouldn't need to trigger the migrations for this package
   * We can't yet add `securedrop-updater` as a dependency as that would break the way we tell people to install the workstation right now. In the future though that would be much preferred over handling this with Salt
7. Merge, test and release!
   * Unfortunately no user facing changes, but at least it should help our future selves out for when Qubes OS R4.2 comes around

**Comment by cfm** [comment]
Prepared in #831; obsoleted by #974.
