### ISSUE TITLE
airgap as a software property of VMs that decrypt or display documents

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop-workstation#81]
> By treating the airgap as a software property of VMs that decrypt or display documents

I'm not a security engineer and unable to figure out what that means exactly. How is this equivalent to having an airgap machine? If it is not exactly equivalent, what are the tradeoffs?

**Comment by eloquence** [comment]
The inelegance in wording is my fault. It may be better to simply say "By disabling Internet access for VMs that deal with decrypted documents or private key material". @conorsch any thoughts?

Regarding the tradeoffs/risks, I agree what's stated so far is completely insufficient to justify more than a pilot. Mickael has done extensive threat model work on the current architecture, and we need to re-validate that threat model against the proposed Qubes architecture. At a high level, @joshuathayer should be able to expand what's currently stated in the README in terms of additional categories of vulnerability we should be concerned about.

**Comment by conorsch** [comment]
I'll admit that the wording caught my eye, as well, as potentially confusing, but my initial efforts to clarify only made the problem worse, e.g. stating explicitly that the surrogate airgap equates to isolation enforced by the hypervisor. 

It's worth pointing out that Qubes gives a high-level response to this very question, about the the airgap/isolation trade-off: https://www.qubes-os.org/intro/#how-does-qubes-os-compare-to-using-a-separate-physical-machine We'd do well to update our language to stress that we're considering the trade-offs in order to provide a more secure overall product. 

As @eloquence indicates, we've done a lot of work on the SD threat model recently, and it's an upcoming ask to leverage that work on assessing the trade-offs involved with the Workstation in a formal manner.
