### ISSUE TITLE
user research explaining the problem

### ISSUE THREAD

**Issue by ghost** [freedomofpress/securedrop-workstation#82]
There is a need for user research to observe the problems in the journalist experience. And based on these observations experiments should be conducted to figure out how to improve the journalist experience. These experiments should not be done assuming the SecureDrop workstation is part of the solution.

It is possible that the user experience of Qubes itself is significantly more difficult than the user experience of Tails. User research can easily be conducted to ask journalists and admins to:

* prepare, use and upgrade Qubes machines instead of Tails
* to select  and buy the hardware to run Qubes instead of Tails

Before engaging into a very significant effort to implement a Qubes based SecureDrop workstation, it is worth checking that there the environment itself does not create blocking problems.

It is also possible that user research concludes that a good journalist workflow could be for the journalist to plug in a USB key, type a passphrase, and have two VMs running in tails, one pulling documents from the net and the other launching a thunderbird with all documents presented as incoming mails (no journalist interface at all).

It is also possible that user research concludes something unexpected that makes the above irrelevant.

**Comment by eloquence** [comment]
Significant user research has been done as part of the SecureDrop Workstation Pilot. https://securedrop.org/news/piloting-securedrop-workstation-qubes-os/ (because of the sensitivity of this information, not all of it is publicly viewable yet, but we'll aim to make more of these documents public pending additional review).

Additional user research is planned for the next stages of the project and will be tracked in the SecureDrop UX repo.
https://github.com/freedomofpress/securedrop-ux/issues
