### ISSUE TITLE
Build and test Workstation base template RPM with updated securedrop-keyring package

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#887]
Once the Bullseye version of securedrop-keyring is available as per https://github.com/freedomofpress/securedrop-builder/issues/443, a new base template should be built and tested containing it.

**Comment by rocodes** [comment]
This upstream issue gives us the biggest clue: https://github.com/QubesOS/qubes-issues/issues/5263#issuecomment-597744172   Even though there is a `make remount` script in qubes builder now, it doesn't seem to have done the trick in our case.  Trying the build again after remounting manually, will update :)

**Comment by rocodes** [comment]
I was not able to successfully build a template, still running into permissions issues that look to be chroot-related. @eaon has latest updates from last week.

**Comment by eaon** [comment]
After having had repeated mount related trouble in upstream dependencies, we pivoted by coming up with a non-standard procedure that for all intents and purposes should not be any different than a template that was updated in-flight.

Instead of building a new template from the ground up, we instead did the following:
1. Downloaded our own template
2. Unpacked its contents
3. Assembled the root image of the template
4. Mounted the root image
5. Used `chroot` to update the system contained within
6. Repackaged the updated image

Since this wasn't scripted but a series of commands, it doesn't really fit anywhere, so I created a [gist](https://gist.github.com/eaon/e48c58bec5dff3a6550f6390da7d4e6e) describing what's being done and why.

Details of the actual build by @rocodes can be found in https://github.com/freedomofpress/build-logs/commit/a3539dcfbfe05fe98f2f21657c38a1519f5a508c 

As I pointed out in my comment in https://github.com/freedomofpress/securedrop-yum-test/pull/48, the installed packages for an _updated in-flight_ template are exactly the same as what's contained in the package.

**Comment by rocodes** [comment]
Thank you so much for testing and instruction @eaon :)  Just a heads up that when I tried to install on my machine, I ran into this upstream issue:
https://github.com/QubesOS/qubes-issues/issues/6297 

Won't affect vanilla SDW installs but for folks installing lots of other templates we should keep up with this issue from a support perspective.

**Comment by eaon** [comment]
Left a note in the issue you referenced so that the whole community may benefit from our new insights :slightly_smiling_face:

**Comment by rocodes** [comment]
Here are some instructions for anyone testing the rpm, which is now on yum-test.securedrop.org

# Test Plan
Hardware:
Scenario: **Clean install*
Prep: 
- Install Qubes 4.1 and perform system updates.
- Next we'll be following a modified version of the prod boostrap  ([instructions](https://workstation.securedrop.org/en/stable/admin/install.html#download-and-install-securedrop-workstation)). Download the [staging dom0 config package](https://yum-test.securedrop.org/workstation/dom0/f32/securedrop-workstation-dom0-config-0.8.0-0.rc2.1.fc32.noarch.rpm), which is signed with the [test key](https://github.com/freedomofpress/securedrop-workstation/blob/2c38e1e76ad9c85f56b51e652f9b6afc4a754598/sd-workstation/securedrop-release-signing-pubkey-2021.asc#L4), verify it, and install it in dom0 using `dnf install` per prod instructions.  
- Ensure that `/etc/yum.repos.d/securedrop-workstation.repo` is pointing to `yum-test.securedrop.org`.
- Finish the rest of the prod instructions for configuring your workstation (key fingerprint, onion particulars, etc).
- Run `sdw-admin --apply`.

- [ ] Installation completes successfully
- [ ] Basic functionality is available in qubes based off securedrop-workstation-bullseye templates (boot, shut down, transfer files between VMs where RPC policies allow, for example: logs from other VMs are entering `sd-log`; `sd-log` can copy files to any VM you tag with `sd-receive-logs`, provided you accept the RPC permissions prompt)

**Comment by rocodes** [comment]
I removed @nathandyer's assignment since there was actually one step missing from the test plan (manually edit `config.json`) and I didn't catch it quick enough, and Nathan's install was already underway (so he ended up with a prod install using the old template rpm, not a staging install using the new one).  

## Test plan
- Hardware: Thinkpad Carbon X1 6gen
- Install: clean install
- [x] Installation completes successfully
- [x] Verified new template is installed (keyring package in `securedrop-workstation-bullseye` is 0.2.1+bullseye)
- [x] Basic functionality is available/no obvious issues - will do more testing tomorrow

**Comment by rocodes** [comment]
@nathandyer Thanks for your offer, no need at present time - but don't worry, we'll make use of your prod setup for the dom0 config package update coming soon. I would never let a good prod workstation go to waste. ;)

**Comment by rocodes** [comment]
Now that https://github.com/freedomofpress/securedrop-yum-prod/pull/43 is up, we will close this issue in favour of the release tracking issue: 
https://github.com/freedomofpress/securedrop-workstation/issues/888
