### ISSUE TITLE
Investigate using Qubes updater in 4.2

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#899]
Qubes 4.2 ships with a new GUI and CLI updater that no longer relies on Salt to update VMs. This means that our existing update method no longer works, but also presents an opportunity to more heavily rely on Qubes' built-in update facilities. The purpose of this issue is to:

- investigate and flesh out what a migration to direct use of the Qubes 4.2 updater could look like;
- identify decisions we need to make about the desired updater behavior
- cross-link upstream issues that could present blockers for such a migration.

*(Issue placeholder fleshed out by @eloquence, 2023-06-08)*

**Comment by eloquence** [comment]
The following flow chart describes the _current_ SecureDrop Workstation preflight updater behavior:

![Screenshot from 2023-06-08 10-40-18](https://github.com/freedomofpress/securedrop-workstation/assets/213636/024a7184-dda0-4fe6-a97b-46baf8151478)

[view/edit](https://mermaid.live/edit#pako:eNqVlMlu2zAQhl9lwFwlIHGXxCpQwPGSpE2BoG57iXqgxZFNmCJVkqorBHn3jijKRg5ddNJo5uM_C5cnVhiBLGNby-sdfLnONYDzrUKYQWGUsdlG8WKfQCmVys6m06KYTjto9piztefWQ1MbDY1DC8pspc7Z9xCHNIWc3ZUUF9yjA17XSqKAg_Q7qUFx5-EKdqaxLmdEv4dr0rznjS52sMaisbiwpoY5rdL-j7LaeLBYEKLaIUfUm5PeytgCgevIW7DNUKJrNn3bHfc1hj8fw4ujF4SpzqN3Sd4ZZWmDE9ZceRpYV0kEVo-hvEqStpc0mlLxLUgHDn3SZQcnDikXFc0gTbuC27jy5pTw2ycHPyUP8jF6S9EHtKWxFYWp5Y0xfkh6F3bDWIxtQoWek8HB6FRItx96CnNZhkaCuQolB_Mm1BDM25AwmHediVp0n_lx-KH3YQcOSHlfTv4D1bPUZT_7WGss4SSiTYzQ50cjLZ0NYwdX3bd6VPz477NxUua6BbTW2Lj4vpudldr3XpqOc3yLCfURzo_6u7CSer8Ol-Kc9tqaPWZnEyzE5UXS_6YHKfwum9S_3r3kL0byk5H8q5H865H8m5H825H85Uj-aiQ__Q-eJaxCW3Ep6B186tbnzO-wwpxlZAosedPdwlw_E9of-qWQdNtYVnLlMGG88Wbd6oJl3jY4QAvJ6Q2oIvX8G_oszcw)

1. The updater starts upon user login
2. If and only if updates have been applied within the last 8 hours, skips ahead to launch SecureDrop Client.
3. Otherwise, it forces an updater run that will perform operations in this order:
- [Update] updates dom0
- [State enforcement, used for some migrations] applies dom0 Salt states (always!)
- [Full migration] if a migration flag is set, also runs sdw-admin --apply
- [Update] Updates the following VMs via Salt: Fedora base template, SecureDrop Workstation large, SecureDrop Workstation small, Whonix gateway base template
- Performs VM reboots
- Stores various update metadata on-disk

Updates are performed sequentially.

4. If dom0 updates were applied, enforces a reboot
5. If reboot has been performed or no reboot required:
- all good: launches the SecureDrop Client
- any error: prints error message, does not launch SecureDrop Client

**Comment by eloquence** [comment]
The Qubes 4.2 GUI updater provides important new facilities that, in principle, give us the option to migrate to the OS-level updater:
- It can keep track of "staleness" of VMs that don't otherwise report the availability of updates (because they're networkless or aren't running)
- It includes the option of restarting VMs after updates
- It keeps track of the update state of each VM (with the caveat that, in our testing, this appears to be still incomplete/brittle)

It also allows for concurrency and should generally be significantly faster than the old update method.

The following flow chart describes what a "minimum viable product" migration to the Qubes 4.2 updater _could_ look like. The details are subject to various team-level decisions, however. 

![Screenshot from 2023-06-08 15-20-56](https://github.com/freedomofpress/securedrop-workstation/assets/213636/e7140631-a0aa-4aac-adfa-b5857b759ad9)

1. Our now much slimmer preflight code runs upon user login and checks the update state of VMs we keep track of (based own Qubes itself tracking this state)
2. If updates haven't been recently applied, we display a brief message to the user asking them to complete a system update.
3. Once the user proceeds, we launch the 4.2 updater. Migrations can run as postinst code if the dom0 package is updated, using the mechanics described in https://github.com/freedomofpress/securedrop-updater/tree/main/migrations
4. We check that the system is in the expected state (i.e. that expected VM updates have been completed, and that migrations have run successfully). 
5. We proceed much like in the current updater flow, except that we check if the expected VMs have in fact been restarted. If not, we do so before launching the SecureDrop Client.

**Comment by eloquence** [comment]
There are a few important decision-points that should influence any "MVP" migration to the 4.2 updater. Here are some we identified:

- Do we want to continue to enforce updates on login? This is an early design decision of the SecureDrop Workstation. If we want to instead rely more on the OS itself to nudge the user about updates, we may want to revisit this. The sketch above assumes that we do not change this behavior for now.

- Do we want to preserve the separate `sdw-notify` script that pops up regularly to remind the user to complete updates if they have not done so? Do we want to advocate for update reminders as a Qubes OS level (upstream) feature to eventually replace it?

- If updates fail, do we want to continue to prevent launching the SecureDrop Client _in all error states_? The sketch above does not go into detail on this; we could be a bit more selective on which failures we consider fatal.

- Do we want to preserve the current mechanics for running `dom0` Salt states or `sdw-admin —apply`? The MVP sketch above assumes that we do not, and that we instead use this opportunity to move towards a more well-defined mechanism for running clearly scoped migrations selectively.

- Do we want to invoke the updater GUI, or wrap the `qubes-vm-update` tool? The MVP sketch above assumes that we invoke the GUI, so that we don't have to effectively re-implement parts of it ourselves.

@eaon, please chime in if I'm missing stuff, if I misunderstood anything from our conversation, or otherwise. :) Beyond that, I think we're nearing the end of our current cycle commitment and can move most of the in-depth discussion of these questions into the planning phase for the next cycle.

**Comment by eaon** [comment]
I think you covered everything we talked about, thanks a lot for summarising it in a concise manner!

The only thing I'd want to expand on at this stage (to give others the chance to think about it):

> If updates fail, do we want to continue to prevent launching the SecureDrop Client in all error states? The MVP sketch above does not go into detail on this; we could be a bit more selective on which failures we consider fatal.

I think given how SDW works, I would continue to treat update failures as fatal. We can't know if the updates are security updates or not, and I'd err on the side of caution. **However**: there is a potential to allow the client to be started with limited functionality: offline-only, showing messages as normal but only file export is enabled.

To elaborate: opening or printing files (same thing) sent by sources when we know there may be a security update waiting for us is probably a bad idea, even if the chances that the file someone is working with that session has that exact exploit are low. Simultaneously, leaving our users with no access to their data is less than ideal UX. How much effort it would be to implement this in the client I don't know, but if it's straight-forward, I'd love if we considered it.

Back to the updater though: my understanding of Qubes Updater is that far more often than not we will _know_ that there's updates, rather than learning about them every day when we enforce an update attempt. So with sourcing out our "check for updates and install them" behaviour to Qubes Updater, we will have a dramatically lower failure rate as we just don't need to run a whole "check for updates and install them" command as often, since it will happen automagically in the background.

**Comment by cfm** [comment]
@eaon, I largely agree with you in <https://github.com/freedomofpress/securedrop-workstation/issues/899#issuecomment-1587555406> and in turn with the MVP positions @eloquence suggests in <https://github.com/freedomofpress/securedrop-workstation/issues/899#issuecomment-1583560608>.

> > If updates fail, do we want to continue to prevent launching the SecureDrop Client in all error states? The MVP sketch above does not go into detail on this; we could be a bit more selective on which failures we consider fatal.
> 
> I think given how SDW works, I would continue to treat update failures as fatal. We can't know if the updates are security updates or not, and I'd err on the side of caution.

I agree with this too.


> **However**: there is a potential to allow the client to be started with limited functionality: offline-only, showing messages as normal but only file export is enabled. (We could go even more granular: offline-only only being applied _if_ the whonix update failed)
> 
> To elaborate: opening or printing files (same thing) sent by sources when we know there may be a security update waiting for us is probably a bad idea, even if the chances that the file someone is working with that session has that exact exploit are low. Simultaneously, leaving our users with no access to their data is less than ideal UX. How much effort it would be to implement this in the client I don't know, but if it's straight-forward, I'd love if we considered it.

This less-than-ideal UX *is* the current behavior.  I believe it's justified by (an admittedly distant) extension of the same logic: even the export/print flows could be compromised by vulnerabilities that pending updates might fix.

If we should decide to break with that cautious approach, I think we could come up with a way (a feature and/or QubesDB value) to expose the system/VM's update state to `sd-app` in order to put the Client into a particular mode.  But I'd want to map that out very carefully:  *Is* this system-level lockdown mode the same as the application-level offline mode?  If not, how are they different?

**Comment by lsd-cat** [comment]
Depending if exporting also involves archiving/unarchiving files with arbitrary or controllable names I tend to agree that the attack surface of a copy operation, given that the copy operation is the only thing that happens and path are safely handled, is practically none. For the printing flow, it depends a lot on what gets printed and how, but I do not have enough knowledge of our processes to assess that now.

**Comment by rocodes** [comment]
Hey @deeplow, this is great, thank you. Super great writeup and I like the flowchart. 

Couple followup questions I'm curious your opinion on. The things we want to accomplish are: a) know if updates succeeded; b) know for which VMs updates failed, if any, and c) prevent the user from starting SDW VMs unless they are updated (ideally without depending on user interaction, i.e. without needing the user to explicitly click "Restart VMs" after the updater run is completed). Do you think we can do the above programatically? 

re the restart possible bug - When I try `qubes-vm-update --restart` with an appvm running whose template needs updates, IME the appvm does indeed restart at the end of the update process. However.... it restarts whether or not the template upgrade was successful :( So it's a different problem that I'm noticing. (I'm going to file an upstream ticket for that)

re the exit status: on the cli, if template updates fail I receive a non-zero exit status (2 in my case).

**Comment by rocodes** [comment]
Yeah, I was specifically testing out the cli because you'd mentioned you'd been testing the GUI more heavily, but aside from how the user interacts, I would expect ~ behaviour parity between the two. (

Right now, we _do_ basically restrict the user from launching the client unless VMs are updated, and that's the main purpose of our updater. (The desktop shortcut launches the client directly if update timestamp is recent enough, or the updater otherwise, and we don't include a menu entry for launching the client. Of course, a very determined user could start an sd-app terminal and type `securedrop-client` to bypass, but this is clearly not the happy path, and our main goal is to make the easy/happy path have as little room for user error/choice around updates as possible).

So my hope would be to invoke the Qubes updater in the same manner. (User tries to launch the client -> updates begin automatically if required, client launches iff updates successful.)  I agree that it's harder to use the GUI to implement conditional logic (and it makes sense to me that a gui app would always exit with 0 unless the gui portion itself crashed), but I'm hopeful we can either use the cli the same way, and/or read from prefs as you suggest and re-launch the GUI updater if we decide that's better, but either way recreate the flow that for now, non-updated vms means the client won't launch.

(fwiw: the gui doesn't seem to miss the "restart" option for me; maybe we can briefly touch base about what you're seeing?)

**Comment by rocodes** [comment]
Had a pairing chat with @deeplow today, just putting our notes/work plan here. He plans to take point on this issue, and I will be available for rubber-ducking/review/assistance throughout. We discussed that the next step will be a pseudocode implementation that preserves the underlying logic (below), and if there's any big changes or hiccups we'll catch it early. 

```
update logic:
    - [on startup] remove reboot flag if set
    - [user clicks sd desktop icon]
         - read last update status from disk. ("Success", "Fail", "Reboot req'd")
           - check reboot flag if so prompt for reboot
           - if failure then launch updater
               - check network access (no network: updater should fail immediately)
               - network access: try updating (meaning: update dom0's packages; update vms's packages)
                   - updates succeed and no reboot needed: 
                     - success timestamp written to disk, success status written to disk
                     - launch client
                   - updates  succeed and reboot needed (dom0 update):
                     - reboot flag written to disk, update success timestamp written to disk
                     - success screen prompts user to reboot
               - updates fail: error
                 - error status written to disk 
                 - log error (launcher, launcher-detail)
                 - report to user
           - if success (good update and update timestamp present and done inside our time window) then launch the client
```

**Open questions/discussed and agreed on points:**
* Is there a nice way we can get away from using a hardcoded list of vm update targets? https://github.com/freedomofpress/securedrop-workstation/blob/db990ce53b057d41590dfe6d3270ca492b57d20d/launcher/sdw_updater_gui/Updater.py#L42 (Future: tags?) and/or: is there a convenient way to set a vm as a target (eg in prefs, vmconfig) without having to look through all a user's VMs?  might be inefficient; everything tagged sd-workstation? - Exploration is OK here)
* Can we get the success or error status from the qubes GUI updater at this point? (Looks like not readily/if not, fall back to qubes updater CLI)
* UI question: if we do invoke the qubes GUI updater should we let them know beforehand ("you will see the Qubes GUI updater launch...") -> yes, if we go that route, (as opposed to having it just pop up with no preflight msg), but see above 

**Explicitly out of scope for this feature:**
*  System integrity checking (deferred)
* Handling migration (switching base templates, things covered by qvm-prefs, etc, aka "orchestration") - we won't aim to solve that with this right now
  * On the topic of migration/orchestration, we may want to modularize it to speed things up and make things clearer to the user, so rather than one `provision all` script we can have sub components)

**Comment by rocodes** [comment]
Hi @deeplow, I came back to add the `restart` thing per our convo but looks like you did it already so ty :) 

I intended the writeup to be implementation-agnostic, so that we could always refer back to it to understand the core logic (eg if we ever switch from cli to gui), but yes I agree with your additions, with one nitpick: dom0 updates and check should come before vm updates, sorry my semicolon list was working a little too hard in the above notes I think. (To your other point, this is where the migration/orchestration stuff will enter into the picture).

So if you're breaking that part down I think it's more like

```
[...]
               - check network access (if no network access: updater should fail immediately)
               - if network access:
                   - check for dom0 updates, then if they're available, try updating dom0 (via a native qubes update mechanism)
                       - if fails: report error and bail, don't continue with the rest of the update attempt
                       - elif succeeds:
                           - write dom0 needs_reboot status to disk 
                           - if needs_migration:
                               - do migration/orchestration stuff (native qubes updater is not responsible for this)
                               - continue    
                   - check for vm updates via native qubes update mechanism. targets: sd-templates, sys-usb, sys-net, sys-firewall
                       - write status to disk 
                       - --restart
```

I think in the best case, we wouldn't restart the vms/templates if no updates were applied, but that's an eventual optimization that is not essential/important compared to the overall logic + consistency (and maybe it's something we can eventually get from upstream).

The `needs_migration` part currently goes like this: if we need to do any 'orchestration' in dom0 and force a full run of our provisioning logic, we drop a (true) flag file during dom0 updates that is installed in basically the [postinst of the new dom0 rpm](https://github.com/freedomofpress/securedrop-workstation/blob/db990ce53b057d41590dfe6d3270ca492b57d20d/rpm-build/SPECS/securedrop-workstation-dom0-config.spec#L126-L128),  and then [picked up on by the updater](https://github.com/freedomofpress/securedrop-workstation/blob/db990ce53b057d41590dfe6d3270ca492b57d20d/launcher/sdw_updater_gui/Updater.py#L95-L103) to decide if the whole salt update will run.

My reasoning is as follows:
- if dom0 updates fail, we know that's a failure state, so tell them asap and don't put them through the pain of continuing to try to update.
- If dom0 updates succeed but require a migration before the system can be in working order, we shouldn't keep trying to update old templates in the same updater run. (eg: suppose we need to ship new templates, rotate a signing key, or something else happens that means that old templates will indefinitely fail to update. The dom0 update goes first, succeeds, then the orchestration/migration runs and tells the system not to keep trying to update those old/stale vms).  If we can accomplish this in all one updater run, that's great, but the way I look at it it's two separate runs, because there may be an 'orchestration' stage in between the runs. (I hope this makes sense).

For the sake of scoping of this feature, I think it makes sense to leave that migration stuff as is for now and just focusing on replacing [our update logic](https://github.com/freedomofpress/securedrop-workstation/blob/db990ce53b057d41590dfe6d3270ca492b57d20d/launcher/sdw_updater_gui/Updater.py#L107-L204) with (a) calll(s) to qubes updater.

We will be able to improve on the migration part as we make more progress on other areas of our architecture overhaul (for example, if more things are in packages, fewer things _require_ a migration; and if orchestration is a bit more modular then we don't have to use the blunt instrument of "run all provisioning" vs "run no provisioning," but we can be a bit more granular about it).

**Comment by zenmonkeykstop** [comment]
Looks good! would be good to add error states in there as well.
