### ISSUE TITLE
Port updates from defunct securedrop-updater repo to securedrop-workstation

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#966]
Code cleanup and general fixes for the current launcher were added in https://github.com/freedomofpress/securedrop-updater - these should be evaluated and pulled back into https://github.com/freedomofpress/securedrop-workstation

- [x] review commits from the last common point: https://docs.google.com/spreadsheets/d/1he6yeZ2frwhMLw7N4bfZQgx61E7-vz3la9axriY-oAk/edit
    - 400f6828bdef49f0ae2f8b937712afe4caf0808c
    - freedomofpress/securedrop-updater@18cacc89fb7c23beeea8f6c36234393d68730ebd
- [x] document what should be kept and why (see #965 for precedent)
- [x] copy desired changes into securedrop-workstation (most likely using the `4_2-compat-keep-launcher` branch as a base)
    - [ ] #966

**Comment by cfm** [comment]
In <https://docs.google.com/spreadsheets/d/1he6yeZ2frwhMLw7N4bfZQgx61E7-vz3la9axriY-oAk/edit#gid=0>, I've done a first pass on `securedrop-updater`'s history from freedomofpress/securedrop-updater@18cacc89fb7c23beeea8f6c36234393d68730ebd, which is its last common point with 400f6828bdef49f0ae2f8b937712afe4caf0808c.  My assumption is that we *do* want to keep versioned migrations as implemented in `securedrop-updater`.  In that case, we'll keep almost everything, excluding some reorganization that'll no longer be applicable.  If that's not a valid assumption, we'll drop freedomofpress/securedrop-updater@69662b9103af8cb7256112a147e571d08b552f0a and freedomofpress/securedrop-updater@ba99a93314837d0378d75cf966e5427c7355dfce and perhaps have some conflicts to resolve as a result.

Pull request forthcoming tomorrow.

**Comment by zenmonkeykstop** [comment]
It's been a while, do you think that the versioned migrations code in particular would still be useful? I'm kindof skeptical - if our goal was to eliminate Salt completely we would need something like them to manage system changes, but:

a) this feels like a brittle solution (eg. miss a version in the migration chain? system state is unknown) and, 
b) I think we're now being more pragmatic about our approach by, for example, seeing how many VM-specific changes we can move into packages. If we end up in a situation where Salt is just managing creation/destruction of VMs, and the contents and config of those VMs are coming from debian packages and configuration injection via qubesdb, the overhead of Salt runs in the event of a migration seems likely to be manageable.

I could be way off here - if there is stuff we can only do via versioned migrations, or if it's easier to write them and they're more robust than I'm making them out to be, it'd be good to document that.

**Comment by cfm** [comment]
I don't know that I would *start* #673 now that we're trying to do as much provisioning as possible in packages.  But we have it already, and I think the rationale of #673 still holds.

@zenmonkeykstop in <https://github.com/freedomofpress/securedrop-workstation/issues/966#issuecomment-2024305809>:

> a) this feels like a brittle solution (eg. miss a version in the migration chain? system state is unknown) [...]

Can you say what you mean by "miss a version"?  If we don't define a migration for a given version, that's a failure on our part.  If we define a migration for a given version, but it doesn't get run, then that's a bug in the migration engine.  As in Alembic, this is just an explicit failure mode, whereas our current approach in both scripting and Salt is an implicit and probably invisible one.

> b) I think we're now being more pragmatic about our approach by, for example, seeing how many VM-specific changes we can move into packages. If we end up in a situation where Salt is just managing creation/destruction of VMs, and the contents and config of those VMs are coming from debian packages and configuration injection via qubesdb, the overhead of Salt runs in the event of a migration seems likely to be manageable.

I agree with your premise here: a lot of the VM-level changes for which we thought we'd have to write migrations will now be handled by packages, which means less Salt.  But I think all of the dom0-level changes in (e.g.) freedomofpress/securedrop-updater#28 would still benefit from explicit migration, whether we keep VM setup in Salt or translate it into migrations.

**Comment by zenmonkeykstop** [comment]
wrt the missing version point, consider first alembic's versioning system. it has a few things going for it: first, SQL is inherently declarative, so defining a desired state is easy; second, alembic is the only thing operating on the schema, so it has complete control of it; third, it works from a linearised history, with each migration step defining its parent and alembic reconstructing and validating said history from that (effectively doing a backward pass before the forward one).

The versioned migration code has none of that going for it, which is why it looks brittle to me. Because files etc are going to be installed and modified by regular rpm operations, versioned migration scripts may try to operate on objects that either don't exist, (coz, say, a user on 1.0.0 skipped version 1.1.0 where it was added, and is now installing 1.2.0), or have been modified in ways the script can't anticipate. It also doesn't have the benefit of a linear history (for the same reason - we can't guarantee that new versions are being installed in strict sequence).

Salt has its woes, but it also supports declarative definitions, and it is more feature-complete - we would have to add to the versioned migrations code to support qubes admin-type operations, for example. Reducing the amount it has to do through the other means we have planned will reduce overall execution time, but IMO eliminating it completely and using the versioned migration code would require a lot more work to get the same level of functionality. Basically I remain unconvinced.

**Comment by cfm** [comment]
@zenmonkeykstop and I discussed this further.  I'll proceed with rebasing this work (as is) into `securedrop-workstation`, and next week we'll discuss with the team whether we want to keep versioned migrations in addition to package-based provisioning of `dom0` and Salt configuration.  If we do keep it, we'll time-box any follow-up work and testing it may require.

**Comment by legoktm** [comment]
In general I think the versioned migrations model in the updater repo is sound. I think it's a little tough to discuss in abstract without concrete examples of things we'd like to migrate. My stance would be that we do a bit of wait and see based on what we end up needing to migrate in the future. My understanding is that @cfm has already done the work to bring it back into this repo, so I'd stick with that, and after a few releases if we find it isn't working, we remove it / adjust path.

The context that I feel is missing here is that historically we've had a lot of pain with salt (not to mention the uncertainty around salt's future) that I don't think we were/are super interested in making it even more of a thing? Like, I'd rather work putting stuff in rpm, including having migrations run by rpm instead of salt.

**Comment by cfm** [comment]
We discussed this in today's team meeting and were approximately split across options:
1. releasing this for the Qubes 4.2‒based Workstation from the get-go;
2. dropping this; and
3. deferring this to a future release.

One theme of discussion was that we want to make sure that we stay true to the [principles](https://wiki.freedom.press/wiki/SecureDrop_Development/Principles_and_assumptions) we drafted in November, in particular:

> (3) One true way to enforce system configuration.
> 
> (6) Salt + RPM packages for dom0; QubesDB + systemd + Debian packages for VMs.

I believe that using the RPM `post` scriptlet to make changes via versioned migrations, rather than making those changes directly from the scriptlet, in no way violates (6).  It refines a provisioning path; it doesn't introduce a new one.

On the one hand, this is the ideal moment to introduce this facility, since this Workstation release will be installed onto a clean-slate Qubes 4.2 system.  That means we'll begin defining subsequent migrations from a known state.

On the other hand, we don't have consensus on this approach.  Deferring it to the subsequent release (i.e., Qubes 4.2 compatibility + 1 version) would let us use whatever `dom0` changes it includes as a concrete example and test case, like freedomofpress/securedrop-updater#28.

After discussion and consideration, that's my new recommendation: Prioritize Qubes 4.2 compatibility without versioned migrations, and use the very next release as a final go/no-go decision for whether to pull in this facility, based in part on the `dom0` changes actually under consideration at that time.
