### ISSUE TITLE
Remove backwards compatibility with old qubes-rpc directives

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-workstation#968]

**Comment by rocodes** [comment]
I initially wasn't sure which approach was better (the two being disable/modify the 35-compat.policy, or make our policy files a higher priority), but now that I've had a chance to sleep on it, I think we should go for the second option. So I'm in favour of
* re-prioritizing 60-securedrop-workstation.policy and 70-securedrop-workstation.policy to numbers < 35  (possibly with flipping their order, so that the allow file comes first, then the deny file)
  * Probably actually to numbers <= 32, since it would be friendly to leave room for end users to add their own additional custom policy file(s) before compat files load 
* ensuring our dom0 tests test rpc policies
* deleting our old style policy modifications (`/etc/qubes-rpc/qubes.USB`, `/etc/qubes-rpc/qubes.USBAttach`, `/etc/qubes-rpc/qubes.ClipboardPaste`, `/etc/qubes-rpc/qubes.PdfConvert`, `/etc/qubes-rpc/qubes.Gpg`, and `/etc/qubes-rpc/qubes.GpgImportKey`

**Comment by rocodes** [comment]
See also #964

**Comment by zenmonkeykstop** [comment]
No argument here, go for it!
